
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun Mar 10 22:49:01 CST 2019
//----------------------------------------------------

package Analizadores.Gdato;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int div = 13;
  public static final int principalF1 = 9;
  public static final int listaF1 = 6;
  public static final int menq = 3;
  public static final int EOF = 0;
  public static final int idA2 = 11;
  public static final int idA1 = 10;
  public static final int explicit = 2;
  public static final int mayq = 4;
  public static final int error = 1;
  public static final int idF1 = 12;
  public static final int principalA2 = 8;
  public static final int principalA1 = 7;
  public static final int listaA1 = 5;
}

