/* The following code was generated by JFlex 1.4.3 on 15/02/19 10:27 PM */


package Analizadores.Gxml;


import java.util.LinkedList;
import java_cup.runtime.*;

/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.4.3
 * on 15/02/19 10:27 PM from the specification file
 * <tt>src/Analizadores/Gxml/lexicogxml.flex</tt>
 */
public class LexGxml implements java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\5\1\3\1\2\1\0\1\3\1\1\16\5\4\0\1\3\1\0"+
    "\1\10\1\0\1\4\3\0\2\11\3\0\1\46\1\7\1\12\12\6"+
    "\1\0\1\16\1\20\1\13\1\17\2\0\1\27\1\42\1\33\1\34"+
    "\1\31\1\37\1\45\1\43\1\21\2\4\1\36\1\22\1\32\1\24"+
    "\1\23\1\4\1\25\1\40\1\26\1\41\1\30\1\4\1\35\1\44"+
    "\1\4\4\0\1\4\1\0\1\27\1\42\1\33\1\34\1\31\1\37"+
    "\1\45\1\43\1\21\2\4\1\36\1\22\1\32\1\24\1\23\1\4"+
    "\1\25\1\40\1\26\1\41\1\30\1\4\1\35\1\44\1\4\1\14"+
    "\1\5\1\15\1\0\41\5\2\0\4\4\4\0\1\4\2\0\1\5"+
    "\7\0\1\4\4\0\1\4\5\0\27\4\1\0\37\4\1\0\u01ca\4"+
    "\4\0\14\4\16\0\5\4\7\0\1\4\1\0\1\4\21\0\160\5"+
    "\5\4\1\0\2\4\2\0\4\4\10\0\1\4\1\0\3\4\1\0"+
    "\1\4\1\0\24\4\1\0\123\4\1\0\213\4\1\0\5\5\2\0"+
    "\236\4\11\0\46\4\2\0\1\4\7\0\47\4\7\0\1\4\1\0"+
    "\55\5\1\0\1\5\1\0\2\5\1\0\2\5\1\0\1\5\10\0"+
    "\33\4\5\0\3\4\15\0\5\5\6\0\1\4\4\0\13\5\5\0"+
    "\53\4\25\5\12\6\4\0\2\4\1\5\143\4\1\0\1\4\10\5"+
    "\1\0\6\5\2\4\2\5\1\0\4\5\2\4\12\6\3\4\2\0"+
    "\1\4\17\0\1\5\1\4\1\5\36\4\33\5\2\0\131\4\13\5"+
    "\1\4\16\0\12\6\41\4\11\5\2\4\4\0\1\4\5\0\26\4"+
    "\4\5\1\4\11\5\1\4\3\5\1\4\5\5\22\0\31\4\3\5"+
    "\104\0\1\4\1\0\13\4\67\0\33\5\1\0\4\5\66\4\3\5"+
    "\1\4\22\5\1\4\7\5\12\4\2\5\2\0\12\6\1\0\7\4"+
    "\1\0\7\4\1\0\3\5\1\0\10\4\2\0\2\4\2\0\26\4"+
    "\1\0\7\4\1\0\1\4\3\0\4\4\2\0\1\5\1\4\7\5"+
    "\2\0\2\5\2\0\3\5\1\4\10\0\1\5\4\0\2\4\1\0"+
    "\3\4\2\5\2\0\12\6\4\4\7\0\1\4\5\0\3\5\1\0"+
    "\6\4\4\0\2\4\2\0\26\4\1\0\7\4\1\0\2\4\1\0"+
    "\2\4\1\0\2\4\2\0\1\5\1\0\5\5\4\0\2\5\2\0"+
    "\3\5\3\0\1\5\7\0\4\4\1\0\1\4\7\0\12\6\2\5"+
    "\3\4\1\5\13\0\3\5\1\0\11\4\1\0\3\4\1\0\26\4"+
    "\1\0\7\4\1\0\2\4\1\0\5\4\2\0\1\5\1\4\10\5"+
    "\1\0\3\5\1\0\3\5\2\0\1\4\17\0\2\4\2\5\2\0"+
    "\12\6\1\0\1\4\17\0\3\5\1\0\10\4\2\0\2\4\2\0"+
    "\26\4\1\0\7\4\1\0\2\4\1\0\5\4\2\0\1\5\1\4"+
    "\7\5\2\0\2\5\2\0\3\5\10\0\2\5\4\0\2\4\1\0"+
    "\3\4\2\5\2\0\12\6\1\0\1\4\20\0\1\5\1\4\1\0"+
    "\6\4\3\0\3\4\1\0\4\4\3\0\2\4\1\0\1\4\1\0"+
    "\2\4\3\0\2\4\3\0\3\4\3\0\14\4\4\0\5\5\3\0"+
    "\3\5\1\0\4\5\2\0\1\4\6\0\1\5\16\0\12\6\11\0"+
    "\1\4\7\0\3\5\1\0\10\4\1\0\3\4\1\0\27\4\1\0"+
    "\12\4\1\0\5\4\3\0\1\4\7\5\1\0\3\5\1\0\4\5"+
    "\7\0\2\5\1\0\2\4\6\0\2\4\2\5\2\0\12\6\22\0"+
    "\2\5\1\0\10\4\1\0\3\4\1\0\27\4\1\0\12\4\1\0"+
    "\5\4\2\0\1\5\1\4\7\5\1\0\3\5\1\0\4\5\7\0"+
    "\2\5\7\0\1\4\1\0\2\4\2\5\2\0\12\6\1\0\2\4"+
    "\17\0\2\5\1\0\10\4\1\0\3\4\1\0\51\4\2\0\1\4"+
    "\7\5\1\0\3\5\1\0\4\5\1\4\10\0\1\5\10\0\2\4"+
    "\2\5\2\0\12\6\12\0\6\4\2\0\2\5\1\0\22\4\3\0"+
    "\30\4\1\0\11\4\1\0\1\4\2\0\7\4\3\0\1\5\4\0"+
    "\6\5\1\0\1\5\1\0\10\5\22\0\2\5\15\0\60\4\1\5"+
    "\2\4\7\5\4\0\10\4\10\5\1\0\12\6\47\0\2\4\1\0"+
    "\1\4\2\0\2\4\1\0\1\4\2\0\1\4\6\0\4\4\1\0"+
    "\7\4\1\0\3\4\1\0\1\4\1\0\1\4\2\0\2\4\1\0"+
    "\4\4\1\5\2\4\6\5\1\0\2\5\1\4\2\0\5\4\1\0"+
    "\1\4\1\0\6\5\2\0\12\6\2\0\4\4\40\0\1\4\27\0"+
    "\2\5\6\0\12\6\13\0\1\5\1\0\1\5\1\0\1\5\4\0"+
    "\2\5\10\4\1\0\44\4\4\0\24\5\1\0\2\5\5\4\13\5"+
    "\1\0\44\5\11\0\1\5\71\0\53\4\24\5\1\4\12\6\6\0"+
    "\6\4\4\5\4\4\3\5\1\4\3\5\2\4\7\5\3\4\4\5"+
    "\15\4\14\5\1\4\1\5\12\6\4\5\2\0\46\4\1\0\1\4"+
    "\5\0\1\4\2\0\53\4\1\0\u014d\4\1\0\4\4\2\0\7\4"+
    "\1\0\1\4\1\0\4\4\2\0\51\4\1\0\4\4\2\0\41\4"+
    "\1\0\4\4\2\0\7\4\1\0\1\4\1\0\4\4\2\0\17\4"+
    "\1\0\71\4\1\0\4\4\2\0\103\4\2\0\3\5\40\0\20\4"+
    "\20\0\125\4\14\0\u026c\4\2\0\21\4\1\0\32\4\5\0\113\4"+
    "\3\0\3\4\17\0\15\4\1\0\4\4\3\5\13\0\22\4\3\5"+
    "\13\0\22\4\2\5\14\0\15\4\1\0\3\4\1\0\2\5\14\0"+
    "\64\4\40\5\3\0\1\4\3\0\2\4\1\5\2\0\12\6\41\0"+
    "\3\5\2\0\12\6\6\0\130\4\10\0\51\4\1\5\1\4\5\0"+
    "\106\4\12\0\35\4\3\0\14\5\4\0\14\5\12\0\12\6\36\4"+
    "\2\0\5\4\13\0\54\4\4\0\21\5\7\4\2\5\6\0\12\6"+
    "\46\0\27\4\5\5\4\0\65\4\12\5\1\0\35\5\2\0\1\5"+
    "\12\6\6\0\12\6\15\0\1\4\130\0\5\5\57\4\21\5\7\4"+
    "\4\0\12\6\21\0\11\5\14\0\3\5\36\4\15\5\2\4\12\6"+
    "\54\4\16\5\14\0\44\4\24\5\10\0\12\6\3\0\3\4\12\6"+
    "\44\4\122\0\3\5\1\0\25\5\4\4\1\5\4\4\3\5\2\4"+
    "\11\0\300\4\47\5\25\0\4\5\u0116\4\2\0\6\4\2\0\46\4"+
    "\2\0\6\4\2\0\10\4\1\0\1\4\1\0\1\4\1\0\1\4"+
    "\1\0\37\4\2\0\65\4\1\0\7\4\1\0\1\4\3\0\3\4"+
    "\1\0\7\4\3\0\4\4\2\0\6\4\4\0\15\4\5\0\3\4"+
    "\1\0\7\4\16\0\5\5\32\0\5\5\20\0\2\4\23\0\1\4"+
    "\13\0\5\5\5\0\6\5\1\0\1\4\15\0\1\4\20\0\15\4"+
    "\3\0\33\4\25\0\15\5\4\0\1\5\3\0\14\5\21\0\1\4"+
    "\4\0\1\4\2\0\12\4\1\0\1\4\3\0\5\4\6\0\1\4"+
    "\1\0\1\4\1\0\1\4\1\0\4\4\1\0\13\4\2\0\4\4"+
    "\5\0\5\4\4\0\1\4\21\0\51\4\u0a77\0\57\4\1\0\57\4"+
    "\1\0\205\4\6\0\4\4\3\5\2\4\14\0\46\4\1\0\1\4"+
    "\5\0\1\4\2\0\70\4\7\0\1\4\17\0\1\5\27\4\11\0"+
    "\7\4\1\0\7\4\1\0\7\4\1\0\7\4\1\0\7\4\1\0"+
    "\7\4\1\0\7\4\1\0\7\4\1\0\40\5\57\0\1\4\u01d5\0"+
    "\3\4\31\0\11\4\6\5\1\0\5\4\2\0\5\4\4\0\126\4"+
    "\2\0\2\5\2\0\3\4\1\0\132\4\1\0\4\4\5\0\51\4"+
    "\3\0\136\4\21\0\33\4\65\0\20\4\u0200\0\u19b6\4\112\0\u51cd\4"+
    "\63\0\u048d\4\103\0\56\4\2\0\u010d\4\3\0\20\4\12\6\2\4"+
    "\24\0\57\4\1\5\4\0\12\5\1\0\31\4\7\0\1\5\120\4"+
    "\2\5\45\0\11\4\2\0\147\4\2\0\4\4\1\0\4\4\14\0"+
    "\13\4\115\0\12\4\1\5\3\4\1\5\4\4\1\5\27\4\5\5"+
    "\20\0\1\4\7\0\64\4\14\0\2\5\62\4\21\5\13\0\12\6"+
    "\6\0\22\5\6\4\3\0\1\4\4\0\12\6\34\4\10\5\2\0"+
    "\27\4\15\5\14\0\35\4\3\0\4\5\57\4\16\5\16\0\1\4"+
    "\12\6\46\0\51\4\16\5\11\0\3\4\1\5\10\4\2\5\2\0"+
    "\12\6\6\0\27\4\3\0\1\4\1\5\4\0\60\4\1\5\1\4"+
    "\3\5\2\4\2\5\5\4\2\5\1\4\1\5\1\4\30\0\3\4"+
    "\2\0\13\4\5\5\2\0\3\4\2\5\12\0\6\4\2\0\6\4"+
    "\2\0\6\4\11\0\7\4\1\0\7\4\221\0\43\4\10\5\1\0"+
    "\2\5\2\0\12\6\6\0\u2ba4\4\14\0\27\4\4\0\61\4\u2104\0"+
    "\u016e\4\2\0\152\4\46\0\7\4\14\0\5\4\5\0\1\4\1\5"+
    "\12\4\1\0\15\4\1\0\5\4\1\0\1\4\1\0\2\4\1\0"+
    "\2\4\1\0\154\4\41\0\u016b\4\22\0\100\4\2\0\66\4\50\0"+
    "\15\4\3\0\20\5\20\0\7\5\14\0\2\4\30\0\3\4\31\0"+
    "\1\4\6\0\5\4\1\0\207\4\2\0\1\5\4\0\1\4\13\0"+
    "\12\6\7\0\32\4\4\0\1\4\1\0\32\4\13\0\131\4\3\0"+
    "\6\4\2\0\6\4\2\0\6\4\2\0\3\4\3\0\2\4\3\0"+
    "\2\4\22\0\3\5\1\0\1\5\2\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\1\1\2\3\3\1\4\1\5\2\2\1\6\1\7"+
    "\1\10\1\11\1\12\1\13\1\14\13\4\1\15\2\4"+
    "\1\16\1\0\1\1\1\0\1\17\7\0\1\20\10\0"+
    "\1\4\1\21\26\4\20\0\7\4\1\22\20\4\20\0"+
    "\4\4\1\23\1\4\1\24\3\4\1\25\10\4\1\26"+
    "\3\4\15\0\1\27\2\0\5\4\1\30\1\31\1\4"+
    "\1\0\6\4\1\32\4\4\5\0\1\33\4\0\1\34"+
    "\6\0\1\4\1\35\1\36\2\4\1\37\1\0\1\4"+
    "\1\40\6\4\1\41\1\0\1\42\10\0\1\43\4\0"+
    "\5\4\1\0\1\4\1\44\1\45\1\4\1\46\1\47"+
    "\1\4\1\0\1\50\6\0\1\51\1\52\1\0\1\53"+
    "\1\0\5\4\1\0\1\54\2\4\1\0\1\55\1\0"+
    "\1\56\1\0\1\57\3\0\1\60\4\4\1\0\2\4"+
    "\6\0\1\61\1\62\2\4\1\0\1\63\1\64\3\0"+
    "\1\65\1\66\1\67\1\4\1\70\1\0\1\71\1\72"+
    "\1\73\1\4\1\0\1\74\4\0\1\75";

  private static int [] zzUnpackAction() {
    int [] result = new int[323];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\47\0\116\0\165\0\47\0\234\0\303\0\352"+
    "\0\u0111\0\u0138\0\47\0\47\0\47\0\47\0\u015f\0\u0186"+
    "\0\u01ad\0\u01d4\0\u01fb\0\u0222\0\u0249\0\u0270\0\u0297\0\u02be"+
    "\0\u02e5\0\u030c\0\u0333\0\234\0\u035a\0\u0381\0\234\0\352"+
    "\0\352\0\u0111\0\47\0\u03a8\0\u03cf\0\u03f6\0\u041d\0\u0444"+
    "\0\u046b\0\u015f\0\47\0\u0492\0\u04b9\0\u04e0\0\u0507\0\u052e"+
    "\0\u0555\0\u057c\0\u05a3\0\u05ca\0\234\0\u05f1\0\u0618\0\u063f"+
    "\0\u0666\0\u068d\0\u06b4\0\u06db\0\u0702\0\u0729\0\u0750\0\u0777"+
    "\0\u079e\0\u07c5\0\u07ec\0\u0813\0\u083a\0\u0861\0\u0888\0\u08af"+
    "\0\u08d6\0\u08fd\0\u0924\0\u094b\0\u0972\0\u0999\0\u09c0\0\u09e7"+
    "\0\u0a0e\0\u0a35\0\u0a5c\0\u0a83\0\u0aaa\0\u0ad1\0\u0af8\0\u0b1f"+
    "\0\u0b46\0\u0b6d\0\u0b94\0\u0bbb\0\u0be2\0\u0c09\0\u0c30\0\u0c57"+
    "\0\u0c7e\0\u0ca5\0\234\0\u0ccc\0\u0cf3\0\u0d1a\0\u0d41\0\u0d68"+
    "\0\u0d8f\0\u0db6\0\u0ddd\0\u0e04\0\u0e2b\0\u0e52\0\u0e79\0\u0ea0"+
    "\0\u0ec7\0\u0eee\0\u0f15\0\u0f3c\0\u0f63\0\u0f8a\0\u0fb1\0\u0fd8"+
    "\0\u0fff\0\u1026\0\u104d\0\u1074\0\u109b\0\u10c2\0\u10e9\0\u1110"+
    "\0\u1137\0\u115e\0\u1185\0\u11ac\0\u11d3\0\u11fa\0\u1221\0\234"+
    "\0\u1248\0\234\0\u126f\0\u1296\0\u12bd\0\234\0\u12e4\0\u130b"+
    "\0\u1332\0\u1359\0\u1380\0\u13a7\0\u13ce\0\u13f5\0\234\0\u141c"+
    "\0\u1443\0\u146a\0\u1491\0\u14b8\0\u14df\0\u1506\0\u152d\0\u1554"+
    "\0\u157b\0\u15a2\0\u15c9\0\u15f0\0\u1617\0\u163e\0\u1665\0\47"+
    "\0\u168c\0\u16b3\0\u16da\0\u1701\0\u1728\0\u174f\0\u1776\0\234"+
    "\0\234\0\u179d\0\u17c4\0\u17eb\0\u1812\0\u1839\0\u1860\0\u1887"+
    "\0\u18ae\0\234\0\u18d5\0\u18fc\0\u1923\0\u194a\0\u1971\0\u1998"+
    "\0\u19bf\0\u19e6\0\u1a0d\0\47\0\u1a34\0\u1a5b\0\u1a82\0\u1aa9"+
    "\0\47\0\u1ad0\0\u1af7\0\u1b1e\0\u1b45\0\u1b6c\0\u1b93\0\u1bba"+
    "\0\234\0\234\0\u1be1\0\u1c08\0\u1c2f\0\u1c56\0\u1c7d\0\234"+
    "\0\u1ca4\0\u1ccb\0\u1cf2\0\u1d19\0\u1d40\0\u1d67\0\234\0\u1d8e"+
    "\0\47\0\u1db5\0\u1ddc\0\u1e03\0\u1e2a\0\u1e51\0\u1e78\0\u1e9f"+
    "\0\u1ec6\0\47\0\u1eed\0\u1f14\0\u1f3b\0\u1f62\0\u1f89\0\u1fb0"+
    "\0\u1fd7\0\u1ffe\0\u2025\0\u204c\0\u2073\0\234\0\234\0\u209a"+
    "\0\234\0\234\0\u20c1\0\u20e8\0\47\0\u210f\0\u2136\0\u215d"+
    "\0\u2184\0\u21ab\0\u21d2\0\47\0\47\0\u21f9\0\47\0\u2220"+
    "\0\u2247\0\u226e\0\u2295\0\u22bc\0\u22e3\0\u230a\0\47\0\u2331"+
    "\0\u2358\0\u237f\0\47\0\u23a6\0\47\0\u23cd\0\47\0\u23f4"+
    "\0\u241b\0\u2442\0\47\0\u2469\0\u2490\0\u24b7\0\u24de\0\u2505"+
    "\0\u252c\0\u2553\0\u257a\0\u25a1\0\u25c8\0\u25ef\0\u2616\0\u263d"+
    "\0\234\0\234\0\u2664\0\u268b\0\u26b2\0\234\0\234\0\u26d9"+
    "\0\u2700\0\u2727\0\47\0\47\0\47\0\u274e\0\234\0\u2775"+
    "\0\47\0\47\0\47\0\u279c\0\u27c3\0\234\0\u27ea\0\u2811"+
    "\0\u2838\0\u285f\0\47";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[323];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\4\1\5\1\6\1\2\1\7\1\10"+
    "\1\11\1\2\1\12\1\13\1\14\1\15\1\16\1\17"+
    "\1\20\1\21\1\22\1\23\1\6\1\24\1\25\1\26"+
    "\1\27\1\30\1\31\1\32\1\33\1\34\1\35\1\36"+
    "\4\6\1\37\1\6\1\2\51\0\1\5\45\0\1\5"+
    "\51\0\3\6\12\0\25\6\7\0\1\7\1\40\45\0"+
    "\1\41\40\0\10\42\1\43\1\0\35\42\22\0\1\44"+
    "\3\0\1\45\2\0\1\46\1\0\1\47\1\50\1\0"+
    "\1\51\10\0\20\52\1\53\26\52\21\0\1\54\1\55"+
    "\3\0\1\56\1\0\1\57\1\60\1\0\1\61\1\62"+
    "\1\0\1\63\14\0\3\6\12\0\1\6\1\64\11\6"+
    "\1\65\11\6\5\0\3\6\12\0\1\66\5\6\1\67"+
    "\11\6\1\70\4\6\5\0\3\6\12\0\6\6\1\71"+
    "\16\6\5\0\3\6\12\0\10\6\1\72\14\6\5\0"+
    "\3\6\12\0\1\73\5\6\1\74\1\6\1\75\14\6"+
    "\5\0\3\6\12\0\11\6\1\76\1\77\2\6\1\100"+
    "\2\6\1\101\4\6\5\0\3\6\12\0\10\6\1\102"+
    "\14\6\5\0\3\6\12\0\11\6\1\103\13\6\5\0"+
    "\3\6\12\0\3\6\1\104\4\6\1\105\14\6\5\0"+
    "\3\6\12\0\3\6\1\106\14\6\1\107\4\6\5\0"+
    "\3\6\12\0\6\6\1\110\1\6\1\111\14\6\5\0"+
    "\3\6\12\0\1\112\24\6\5\0\3\6\12\0\20\6"+
    "\1\113\4\6\42\0\1\114\36\0\1\115\47\0\1\116"+
    "\40\0\1\117\51\0\1\120\1\0\1\121\36\0\1\122"+
    "\47\0\1\123\65\0\1\124\36\0\1\125\46\0\1\126"+
    "\47\0\1\127\40\0\1\130\51\0\1\131\1\0\1\132"+
    "\36\0\1\133\31\0\3\6\12\0\2\6\1\134\22\6"+
    "\5\0\3\6\12\0\11\6\1\135\13\6\5\0\3\6"+
    "\12\0\14\6\1\136\10\6\5\0\3\6\12\0\15\6"+
    "\1\137\7\6\5\0\3\6\12\0\5\6\1\140\17\6"+
    "\5\0\3\6\12\0\16\6\1\141\6\6\5\0\3\6"+
    "\12\0\2\6\1\142\22\6\5\0\3\6\12\0\1\6"+
    "\1\143\23\6\5\0\3\6\12\0\14\6\1\144\10\6"+
    "\5\0\3\6\12\0\12\6\1\145\12\6\5\0\3\6"+
    "\12\0\12\6\1\146\12\6\5\0\3\6\12\0\5\6"+
    "\1\147\17\6\5\0\3\6\12\0\5\6\1\150\17\6"+
    "\5\0\3\6\12\0\11\6\1\151\13\6\5\0\3\6"+
    "\12\0\7\6\1\152\15\6\5\0\3\6\12\0\1\6"+
    "\1\153\23\6\5\0\3\6\12\0\24\6\1\154\5\0"+
    "\3\6\12\0\11\6\1\155\3\6\1\156\7\6\5\0"+
    "\3\6\12\0\4\6\1\157\20\6\5\0\3\6\12\0"+
    "\5\6\1\160\17\6\5\0\3\6\12\0\16\6\1\161"+
    "\6\6\5\0\3\6\12\0\17\6\1\162\5\6\5\0"+
    "\3\6\12\0\10\6\1\163\14\6\37\0\1\164\45\0"+
    "\1\165\41\0\1\166\50\0\1\167\42\0\1\170\57\0"+
    "\1\171\47\0\1\172\31\0\1\173\61\0\1\174\45\0"+
    "\1\175\43\0\1\176\44\0\1\177\50\0\1\200\42\0"+
    "\1\201\57\0\1\202\47\0\1\203\12\0\3\6\12\0"+
    "\3\6\1\204\21\6\5\0\3\6\12\0\1\205\24\6"+
    "\5\0\3\6\12\0\1\206\24\6\5\0\3\6\12\0"+
    "\5\6\1\207\17\6\5\0\3\6\12\0\22\6\1\210"+
    "\2\6\5\0\3\6\12\0\10\6\1\211\14\6\5\0"+
    "\3\6\12\0\3\6\1\212\21\6\5\0\3\6\12\0"+
    "\5\6\1\213\17\6\5\0\3\6\12\0\22\6\1\214"+
    "\2\6\5\0\3\6\12\0\1\215\24\6\5\0\3\6"+
    "\12\0\3\6\1\216\21\6\5\0\3\6\12\0\3\6"+
    "\1\217\21\6\5\0\3\6\12\0\5\6\1\220\17\6"+
    "\5\0\3\6\12\0\1\221\24\6\5\0\3\6\12\0"+
    "\21\6\1\222\3\6\5\0\3\6\12\0\4\6\1\223"+
    "\20\6\5\0\3\6\12\0\5\6\1\224\17\6\5\0"+
    "\3\6\12\0\3\6\1\225\21\6\5\0\3\6\12\0"+
    "\17\6\1\226\5\6\5\0\3\6\12\0\3\6\1\227"+
    "\21\6\5\0\3\6\12\0\10\6\1\230\14\6\5\0"+
    "\3\6\12\0\5\6\1\231\17\6\5\0\3\6\12\0"+
    "\11\6\1\232\13\6\27\0\1\233\46\0\1\234\41\0"+
    "\1\235\53\0\1\236\44\0\1\237\53\0\1\240\43\0"+
    "\1\241\44\0\1\242\50\0\1\243\46\0\1\244\46\0"+
    "\1\245\41\0\1\246\53\0\1\247\44\0\1\250\53\0"+
    "\1\251\43\0\1\252\24\0\3\6\12\0\4\6\1\253"+
    "\20\6\5\0\3\6\12\0\1\6\1\254\23\6\5\0"+
    "\3\6\12\0\1\6\1\255\23\6\5\0\3\6\12\0"+
    "\1\256\24\6\5\0\3\6\12\0\4\6\1\257\20\6"+
    "\5\0\3\6\12\0\3\6\1\260\21\6\5\0\3\6"+
    "\12\0\3\6\1\261\21\6\5\0\3\6\12\0\3\6"+
    "\1\262\21\6\5\0\3\6\12\0\25\6\1\263\4\0"+
    "\3\6\12\0\6\6\1\264\16\6\5\0\3\6\12\0"+
    "\6\6\1\265\16\6\5\0\3\6\12\0\4\6\1\266"+
    "\20\6\5\0\3\6\12\0\1\267\24\6\5\0\3\6"+
    "\12\0\4\6\1\270\3\6\1\271\14\6\5\0\3\6"+
    "\12\0\4\6\1\272\20\6\5\0\3\6\12\0\1\273"+
    "\24\6\5\0\3\6\12\0\12\6\1\274\12\6\5\0"+
    "\3\6\12\0\6\6\1\275\16\6\5\0\3\6\12\0"+
    "\5\6\1\276\17\6\22\0\1\277\51\0\1\300\51\0"+
    "\1\301\44\0\1\302\3\0\1\303\34\0\1\304\62\0"+
    "\1\305\42\0\1\306\44\0\1\307\42\0\1\310\51\0"+
    "\1\311\51\0\1\312\46\0\1\313\44\0\1\314\3\0"+
    "\1\315\50\0\1\316\42\0\1\317\23\0\3\6\12\0"+
    "\5\6\1\320\17\6\5\0\3\6\12\0\3\6\1\321"+
    "\21\6\5\0\3\6\12\0\3\6\1\322\21\6\5\0"+
    "\3\6\12\0\1\6\1\323\23\6\5\0\3\6\12\0"+
    "\10\6\1\324\14\6\5\0\3\6\12\0\11\6\1\325"+
    "\13\6\26\0\1\326\25\0\3\6\12\0\11\6\1\327"+
    "\13\6\5\0\3\6\12\0\4\6\1\330\20\6\5\0"+
    "\3\6\12\0\10\6\1\212\14\6\5\0\3\6\12\0"+
    "\5\6\1\331\17\6\5\0\3\6\12\0\3\6\1\332"+
    "\21\6\5\0\3\6\12\0\11\6\1\333\13\6\5\0"+
    "\3\6\12\0\7\6\1\334\15\6\5\0\3\6\12\0"+
    "\5\6\1\335\17\6\5\0\3\6\12\0\13\6\1\336"+
    "\11\6\5\0\3\6\12\0\10\6\1\337\14\6\23\0"+
    "\1\340\43\0\1\341\54\0\1\342\45\0\1\343\54\0"+
    "\1\344\42\0\1\345\54\0\1\346\40\0\1\347\42\0"+
    "\1\350\56\0\1\351\41\0\1\352\45\0\1\353\54\0"+
    "\1\354\42\0\1\355\54\0\1\356\16\0\3\6\12\0"+
    "\6\6\1\357\16\6\5\0\3\6\12\0\10\6\1\360"+
    "\14\6\5\0\3\6\12\0\11\6\1\361\13\6\5\0"+
    "\3\6\12\0\1\362\15\6\1\363\6\6\32\0\1\364"+
    "\21\0\3\6\12\0\6\6\1\365\16\6\5\0\3\6"+
    "\12\0\6\6\1\366\16\6\5\0\3\6\12\0\15\6"+
    "\1\367\7\6\5\0\3\6\12\0\10\6\1\370\14\6"+
    "\5\0\3\6\12\0\6\6\1\371\16\6\5\0\3\6"+
    "\12\0\3\6\1\372\21\6\5\0\3\6\12\0\6\6"+
    "\1\373\16\6\32\0\1\374\34\0\1\375\65\0\1\376"+
    "\41\0\1\377\41\0\1\u0100\51\0\1\u0101\46\0\1\u0102"+
    "\50\0\1\u0103\44\0\1\u0104\55\0\1\u0105\41\0\1\u0106"+
    "\41\0\1\u0107\51\0\1\u0108\23\0\3\6\12\0\4\6"+
    "\1\u0109\20\6\5\0\3\6\12\0\13\6\1\u010a\11\6"+
    "\5\0\3\6\12\0\12\6\1\u010b\12\6\5\0\3\6"+
    "\12\0\11\6\1\u010c\13\6\5\0\3\6\12\0\1\u010d"+
    "\24\6\24\0\1\u010e\27\0\3\6\10\0\1\u010f\1\0"+
    "\25\6\5\0\3\6\12\0\13\6\1\u0110\11\6\5\0"+
    "\3\6\12\0\5\6\1\u0111\17\6\35\0\1\u0112\31\0"+
    "\1\u0113\63\0\1\u0114\31\0\1\u0115\55\0\1\u0116\45\0"+
    "\1\u0117\55\0\1\u0118\46\0\1\u0119\40\0\1\u011a\24\0"+
    "\3\6\10\0\1\u011b\1\0\25\6\5\0\3\6\12\0"+
    "\1\u011c\24\6\5\0\3\6\12\0\1\u011d\24\6\5\0"+
    "\3\6\12\0\1\u011e\24\6\5\0\3\6\12\0\11\6"+
    "\1\u011f\13\6\26\0\1\u0120\25\0\3\6\12\0\3\6"+
    "\1\u0121\21\6\5\0\3\6\12\0\3\6\1\u0122\21\6"+
    "\22\0\1\u0123\51\0\1\u0124\46\0\1\u0125\43\0\1\u0126"+
    "\51\0\1\u0127\46\0\1\u0128\26\0\3\6\12\0\6\6"+
    "\1\u0129\16\6\5\0\3\6\12\0\6\6\1\u012a\16\6"+
    "\5\0\3\6\12\0\12\6\1\u012b\12\6\5\0\3\6"+
    "\12\0\6\6\1\u012c\16\6\25\0\1\u012d\26\0\3\6"+
    "\12\0\4\6\1\u012e\20\6\5\0\3\6\12\0\17\6"+
    "\1\u012f\5\6\30\0\1\u0130\44\0\1\u0131\61\0\1\u0132"+
    "\35\0\1\u0133\44\0\1\u0134\61\0\1\u0135\12\0\3\6"+
    "\12\0\1\u0136\24\6\5\0\3\6\12\0\15\6\1\u0137"+
    "\7\6\35\0\1\u0138\31\0\1\u0139\46\0\1\u013a\46\0"+
    "\1\u013b\33\0\3\6\12\0\6\6\1\u013c\16\6\42\0"+
    "\1\u013d\11\0\3\6\12\0\15\6\1\u013e\7\6\34\0"+
    "\1\u013f\46\0\1\u0140\34\0\1\u0141\51\0\1\u0142\54\0"+
    "\1\u0143\14\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[10374];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\1\1\11\2\1\1\11\5\1\4\11\21\1\1\0"+
    "\1\1\1\0\1\11\7\0\1\11\10\0\30\1\20\0"+
    "\30\1\20\0\27\1\15\0\1\11\2\0\10\1\1\0"+
    "\13\1\5\0\1\11\4\0\1\11\6\0\6\1\1\0"+
    "\11\1\1\0\1\11\10\0\1\11\4\0\5\1\1\0"+
    "\7\1\1\0\1\11\6\0\2\11\1\0\1\11\1\0"+
    "\5\1\1\0\1\11\2\1\1\0\1\11\1\0\1\11"+
    "\1\0\1\11\3\0\1\11\4\1\1\0\2\1\6\0"+
    "\4\1\1\0\2\1\3\0\3\11\2\1\1\0\3\11"+
    "\1\1\1\0\1\1\4\0\1\11";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[323];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;


  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public LexGxml(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  public LexGxml(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 2292) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzCurrentPos*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = zzReader.read(zzBuffer, zzEndRead,
                                            zzBuffer.length-zzEndRead);

    if (numRead > 0) {
      zzEndRead+= numRead;
      return false;
    }
    // unlikely but not impossible: read 0 characters, but not at end of stream    
    if (numRead == 0) {
      int c = zzReader.read();
      if (c == -1) {
        return true;
      } else {
        zzBuffer[zzEndRead++] = (char) c;
        return false;
      }     
    }

	// numRead < 0
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      yychar+= zzMarkedPosL-zzStartRead;

      boolean zzR = false;
      for (zzCurrentPosL = zzStartRead; zzCurrentPosL < zzMarkedPosL;
                                                             zzCurrentPosL++) {
        switch (zzBufferL[zzCurrentPosL]) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn++;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL[zzCurrentPosL++];
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL[zzCurrentPosL++];
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 5: 
          { return new Symbol(sym.int_literal, new token(yycolumn, yyline, yytext()));
          }
        case 62: break;
        case 50: 
          { return new Symbol(sym.referencia, new token(yycolumn, yyline, yytext()));
          }
        case 63: break;
        case 49: 
          { System.out.println("tk:"+yytext()); return new Symbol(sym.multimediaA2, new token(yycolumn, yyline, yytext()));
          }
        case 64: break;
        case 42: 
          { System.out.println("tk:"+yytext()); return new Symbol(sym.controlA1, new token(yycolumn, yyline, yytext()));
          }
        case 65: break;
        case 1: 
          { return new Symbol(sym.double_literal, new token(yycolumn, yyline, yytext()));
          }
        case 66: break;
        case 55: 
          { System.out.println("tk:"+yytext()); return new Symbol(sym.listadatosA1, new token(yycolumn, yyline, yytext()));
          }
        case 67: break;
        case 40: 
          { System.out.println("tk:"+yytext()); return new Symbol(sym.enviarF1, new token(yycolumn, yyline, yytext()));
          }
        case 68: break;
        case 27: 
          { System.out.println("tk:"+yytext()); return new Symbol(sym.datoF1, new token(yycolumn, yyline, yytext()));
          }
        case 69: break;
        case 46: 
          { System.out.println("tk:"+yytext()); return new Symbol(sym.defectoF1, new token(yycolumn, yyline, yytext()));
          }
        case 70: break;
        case 7: 
          { return new Symbol(sym.igual, new token(yycolumn, yyline, yytext()));
          }
        case 71: break;
        case 20: 
          { return new Symbol(sym.tipo, new token(yycolumn, yyline, yytext()));
          }
        case 72: break;
        case 53: 
          { System.out.println("tk:"+yytext()); return new Symbol(sym.multimediaA1, new token(yycolumn, yyline, yytext()));
          }
        case 73: break;
        case 21: 
          { return new Symbol(sym.alto, new token(yycolumn, yyline, yytext()));
          }
        case 74: break;
        case 2: 
          { System.out.println(yyline+","+yycolumn+"=["+yytext()+"],"+yychar);
          }
        case 75: break;
        case 15: 
          { return new Symbol(sym.string_literal, new token(yycolumn, yyline, yytext()));
          }
        case 76: break;
        case 44: 
          { System.out.println("tk:"+yytext()); return new Symbol(sym.ventanaF1, new token(yycolumn, yyline, yytext()));
          }
        case 77: break;
        case 16: 
          { System.out.println("tk:"+yytext()); return new Symbol(sym.explicit, new token(yycolumn, yyline, yytext()));
          }
        case 78: break;
        case 12: 
          { System.out.println("tk:"+yytext()); return new Symbol(sym.menq, new token(yycolumn, yyline, yytext()));
          }
        case 79: break;
        case 3: 
          { /* ignorar */
          }
        case 80: break;
        case 58: 
          { System.out.println("tk:"+yytext()); return new Symbol(sym.contenedorF1, new token(yycolumn, yyline, yytext()));
          }
        case 81: break;
        case 4: 
          { return new Symbol(sym.ID, new token(yycolumn, yyline, yytext()));
          }
        case 82: break;
        case 9: 
          { return new Symbol(sym.clla, new token(yycolumn, yyline, yytext()));
          }
        case 83: break;
        case 61: 
          { return new Symbol(sym.autorepro, new token(yycolumn, yyline, yytext()));
          }
        case 84: break;
        case 48: 
          { return new Symbol(sym.importarF1, new token(yycolumn, yyline, yytext()));
          }
        case 85: break;
        case 38: 
          { return new Symbol(sym.cursiva, new token(yycolumn, yyline, yytext()));
          }
        case 86: break;
        case 32: 
          { System.out.println("tk:"+yytext()); return new Symbol(sym.enviarA2, new token(yycolumn, yyline, yytext()));
          }
        case 87: break;
        case 33: 
          { return new Symbol(sym.fuente, new token(yycolumn, yyline, yytext()));
          }
        case 88: break;
        case 30: 
          { return new Symbol(sym.maximo, new token(yycolumn, yyline, yytext()));
          }
        case 89: break;
        case 31: 
          { return new Symbol(sym.accion, new token(yycolumn, yyline, yytext()));
          }
        case 90: break;
        case 22: 
          { System.out.println("tk:"+yytext()); return new Symbol(sym.datoA2, new token(yycolumn, yyline, yytext()));
          }
        case 91: break;
        case 39: 
          { System.out.println("tk:"+yytext()); return new Symbol(sym.defectoA2, new token(yycolumn, yyline, yytext()));
          }
        case 92: break;
        case 60: 
          { return new Symbol(sym.accionini, new token(yycolumn, yyline, yytext()));
          }
        case 93: break;
        case 34: 
          { System.out.println("tk:"+yytext()); return new Symbol(sym.textoF1, new token(yycolumn, yyline, yytext()));
          }
        case 94: break;
        case 10: 
          { return new Symbol(sym.pyc, new token(yycolumn, yyline, yytext()));
          }
        case 95: break;
        case 35: 
          { System.out.println("tk:"+yytext()); return new Symbol(sym.enviarA1, new token(yycolumn, yyline, yytext()));
          }
        case 96: break;
        case 45: 
          { System.out.println("tk:"+yytext()); return new Symbol(sym.controlF1, new token(yycolumn, yyline, yytext()));
          }
        case 97: break;
        case 14: 
          { return new Symbol(sym.y, new token(yycolumn, yyline, yytext()));
          }
        case 98: break;
        case 23: 
          { System.out.println("tk:"+yytext()); return new Symbol(sym.datoA1, new token(yycolumn, yyline, yytext()));
          }
        case 99: break;
        case 43: 
          { System.out.println("tk:"+yytext()); return new Symbol(sym.defectoA1, new token(yycolumn, yyline, yytext()));
          }
        case 100: break;
        case 29: 
          { return new Symbol(sym.minimo, new token(yycolumn, yyline, yytext()));
          }
        case 101: break;
        case 6: 
          { return new Symbol(sym.div, new token(yycolumn, yyline, yytext()));
          }
        case 102: break;
        case 51: 
          { System.out.println("tk:"+yytext()); return new Symbol(sym.contenedorA2, new token(yycolumn, yyline, yytext()));
          }
        case 103: break;
        case 59: 
          { System.out.println("tk:"+yytext()); return new Symbol(sym.listadatosF1, new token(yycolumn, yyline, yytext()));
          }
        case 104: break;
        case 47: 
          { return new Symbol(sym.importarA2, new token(yycolumn, yyline, yytext()));
          }
        case 105: break;
        case 8: 
          { return new Symbol(sym.alla, new token(yycolumn, yyline, yytext()));
          }
        case 106: break;
        case 56: 
          { return new Symbol(sym.accionfin, new token(yycolumn, yyline, yytext()));
          }
        case 107: break;
        case 18: 
          { return new Symbol(sym.tam, new token(yycolumn, yyline, yytext()));
          }
        case 108: break;
        case 41: 
          { System.out.println("tk:"+yytext()); return new Symbol(sym.ventanaA1, new token(yycolumn, yyline, yytext()));
          }
        case 109: break;
        case 13: 
          { return new Symbol(sym.x, new token(yycolumn, yyline, yytext()));
          }
        case 110: break;
        case 24: 
          { System.out.println("tk:"+yytext()); return new Symbol(sym.textoA2, new token(yycolumn, yyline, yytext()));
          }
        case 111: break;
        case 57: 
          { System.out.println("tk:"+yytext()); return new Symbol(sym.multimediaF1, new token(yycolumn, yyline, yytext()));
          }
        case 112: break;
        case 11: 
          { System.out.println("tk:"+yytext()); return new Symbol(sym.mayq, new token(yycolumn, yyline, yytext()));
          }
        case 113: break;
        case 54: 
          { System.out.println("tk:"+yytext()); return new Symbol(sym.contenedorA1, new token(yycolumn, yyline, yytext()));
          }
        case 114: break;
        case 19: 
          { return new Symbol(sym.path, new token(yycolumn, yyline, yytext()));
          }
        case 115: break;
        case 25: 
          { return new Symbol(sym.ancho, new token(yycolumn, yyline, yytext()));
          }
        case 116: break;
        case 37: 
          { System.out.println("tk:"+yytext()); return new Symbol(sym.controlA2, new token(yycolumn, yyline, yytext()));
          }
        case 117: break;
        case 36: 
          { return new Symbol(sym.negrita, new token(yycolumn, yyline, yytext()));
          }
        case 118: break;
        case 26: 
          { return new Symbol(sym.color, new token(yycolumn, yyline, yytext()));
          }
        case 119: break;
        case 52: 
          { System.out.println("tk:"+yytext()); return new Symbol(sym.listadatosA2, new token(yycolumn, yyline, yytext()));
          }
        case 120: break;
        case 28: 
          { System.out.println("tk:"+yytext()); return new Symbol(sym.textoA1, new token(yycolumn, yyline, yytext()));
          }
        case 121: break;
        case 17: 
          { return new Symbol(sym.id, new token(yycolumn, yyline, yytext()));
          }
        case 122: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            zzDoEOF();
              { return new java_cup.runtime.Symbol(sym.EOF); }
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
