/* The following code was generated by JFlex 1.4.3 on 10/03/19 10:56 PM */


package Analizadores.Gxml;


import java.util.LinkedList;
import java_cup.runtime.*;

/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.4.3
 * on 10/03/19 10:56 PM from the specification file
 * <tt>src/Analizadores/Gxml/lexicogxml.flex</tt>
 */
public class LexGxml implements java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\5\1\3\1\2\1\0\1\3\1\1\16\5\4\0\1\3\1\0"+
    "\1\11\1\13\1\14\3\0\2\12\3\0\1\6\1\10\1\15\12\7"+
    "\1\0\1\21\1\23\1\16\1\22\2\0\1\32\1\40\1\36\1\37"+
    "\1\34\1\43\1\50\1\46\1\24\2\4\1\42\1\25\1\35\1\27"+
    "\1\26\1\4\1\30\1\44\1\31\1\45\1\33\1\4\1\41\1\47"+
    "\1\4\4\0\1\4\1\0\1\32\1\40\1\36\1\37\1\34\1\43"+
    "\1\50\1\46\1\24\2\4\1\42\1\25\1\35\1\27\1\26\1\4"+
    "\1\30\1\44\1\31\1\45\1\33\1\4\1\41\1\47\1\4\1\17"+
    "\1\5\1\20\1\0\41\5\2\0\4\4\4\0\1\4\2\0\1\5"+
    "\7\0\1\4\4\0\1\4\5\0\27\4\1\0\37\4\1\0\u01ca\4"+
    "\4\0\14\4\16\0\5\4\7\0\1\4\1\0\1\4\21\0\160\5"+
    "\5\4\1\0\2\4\2\0\4\4\10\0\1\4\1\0\3\4\1\0"+
    "\1\4\1\0\24\4\1\0\123\4\1\0\213\4\1\0\5\5\2\0"+
    "\236\4\11\0\46\4\2\0\1\4\7\0\47\4\7\0\1\4\1\0"+
    "\55\5\1\0\1\5\1\0\2\5\1\0\2\5\1\0\1\5\10\0"+
    "\33\4\5\0\3\4\15\0\5\5\6\0\1\4\4\0\13\5\5\0"+
    "\53\4\25\5\12\7\4\0\2\4\1\5\143\4\1\0\1\4\10\5"+
    "\1\0\6\5\2\4\2\5\1\0\4\5\2\4\12\7\3\4\2\0"+
    "\1\4\17\0\1\5\1\4\1\5\36\4\33\5\2\0\131\4\13\5"+
    "\1\4\16\0\12\7\41\4\11\5\2\4\4\0\1\4\5\0\26\4"+
    "\4\5\1\4\11\5\1\4\3\5\1\4\5\5\22\0\31\4\3\5"+
    "\104\0\1\4\1\0\13\4\67\0\33\5\1\0\4\5\66\4\3\5"+
    "\1\4\22\5\1\4\7\5\12\4\2\5\2\0\12\7\1\0\7\4"+
    "\1\0\7\4\1\0\3\5\1\0\10\4\2\0\2\4\2\0\26\4"+
    "\1\0\7\4\1\0\1\4\3\0\4\4\2\0\1\5\1\4\7\5"+
    "\2\0\2\5\2\0\3\5\1\4\10\0\1\5\4\0\2\4\1\0"+
    "\3\4\2\5\2\0\12\7\4\4\7\0\1\4\5\0\3\5\1\0"+
    "\6\4\4\0\2\4\2\0\26\4\1\0\7\4\1\0\2\4\1\0"+
    "\2\4\1\0\2\4\2\0\1\5\1\0\5\5\4\0\2\5\2\0"+
    "\3\5\3\0\1\5\7\0\4\4\1\0\1\4\7\0\12\7\2\5"+
    "\3\4\1\5\13\0\3\5\1\0\11\4\1\0\3\4\1\0\26\4"+
    "\1\0\7\4\1\0\2\4\1\0\5\4\2\0\1\5\1\4\10\5"+
    "\1\0\3\5\1\0\3\5\2\0\1\4\17\0\2\4\2\5\2\0"+
    "\12\7\1\0\1\4\17\0\3\5\1\0\10\4\2\0\2\4\2\0"+
    "\26\4\1\0\7\4\1\0\2\4\1\0\5\4\2\0\1\5\1\4"+
    "\7\5\2\0\2\5\2\0\3\5\10\0\2\5\4\0\2\4\1\0"+
    "\3\4\2\5\2\0\12\7\1\0\1\4\20\0\1\5\1\4\1\0"+
    "\6\4\3\0\3\4\1\0\4\4\3\0\2\4\1\0\1\4\1\0"+
    "\2\4\3\0\2\4\3\0\3\4\3\0\14\4\4\0\5\5\3\0"+
    "\3\5\1\0\4\5\2\0\1\4\6\0\1\5\16\0\12\7\11\0"+
    "\1\4\7\0\3\5\1\0\10\4\1\0\3\4\1\0\27\4\1\0"+
    "\12\4\1\0\5\4\3\0\1\4\7\5\1\0\3\5\1\0\4\5"+
    "\7\0\2\5\1\0\2\4\6\0\2\4\2\5\2\0\12\7\22\0"+
    "\2\5\1\0\10\4\1\0\3\4\1\0\27\4\1\0\12\4\1\0"+
    "\5\4\2\0\1\5\1\4\7\5\1\0\3\5\1\0\4\5\7\0"+
    "\2\5\7\0\1\4\1\0\2\4\2\5\2\0\12\7\1\0\2\4"+
    "\17\0\2\5\1\0\10\4\1\0\3\4\1\0\51\4\2\0\1\4"+
    "\7\5\1\0\3\5\1\0\4\5\1\4\10\0\1\5\10\0\2\4"+
    "\2\5\2\0\12\7\12\0\6\4\2\0\2\5\1\0\22\4\3\0"+
    "\30\4\1\0\11\4\1\0\1\4\2\0\7\4\3\0\1\5\4\0"+
    "\6\5\1\0\1\5\1\0\10\5\22\0\2\5\15\0\60\4\1\5"+
    "\2\4\7\5\4\0\10\4\10\5\1\0\12\7\47\0\2\4\1\0"+
    "\1\4\2\0\2\4\1\0\1\4\2\0\1\4\6\0\4\4\1\0"+
    "\7\4\1\0\3\4\1\0\1\4\1\0\1\4\2\0\2\4\1\0"+
    "\4\4\1\5\2\4\6\5\1\0\2\5\1\4\2\0\5\4\1\0"+
    "\1\4\1\0\6\5\2\0\12\7\2\0\4\4\40\0\1\4\27\0"+
    "\2\5\6\0\12\7\13\0\1\5\1\0\1\5\1\0\1\5\4\0"+
    "\2\5\10\4\1\0\44\4\4\0\24\5\1\0\2\5\5\4\13\5"+
    "\1\0\44\5\11\0\1\5\71\0\53\4\24\5\1\4\12\7\6\0"+
    "\6\4\4\5\4\4\3\5\1\4\3\5\2\4\7\5\3\4\4\5"+
    "\15\4\14\5\1\4\1\5\12\7\4\5\2\0\46\4\1\0\1\4"+
    "\5\0\1\4\2\0\53\4\1\0\u014d\4\1\0\4\4\2\0\7\4"+
    "\1\0\1\4\1\0\4\4\2\0\51\4\1\0\4\4\2\0\41\4"+
    "\1\0\4\4\2\0\7\4\1\0\1\4\1\0\4\4\2\0\17\4"+
    "\1\0\71\4\1\0\4\4\2\0\103\4\2\0\3\5\40\0\20\4"+
    "\20\0\125\4\14\0\u026c\4\2\0\21\4\1\0\32\4\5\0\113\4"+
    "\3\0\3\4\17\0\15\4\1\0\4\4\3\5\13\0\22\4\3\5"+
    "\13\0\22\4\2\5\14\0\15\4\1\0\3\4\1\0\2\5\14\0"+
    "\64\4\40\5\3\0\1\4\3\0\2\4\1\5\2\0\12\7\41\0"+
    "\3\5\2\0\12\7\6\0\130\4\10\0\51\4\1\5\1\4\5\0"+
    "\106\4\12\0\35\4\3\0\14\5\4\0\14\5\12\0\12\7\36\4"+
    "\2\0\5\4\13\0\54\4\4\0\21\5\7\4\2\5\6\0\12\7"+
    "\46\0\27\4\5\5\4\0\65\4\12\5\1\0\35\5\2\0\1\5"+
    "\12\7\6\0\12\7\15\0\1\4\130\0\5\5\57\4\21\5\7\4"+
    "\4\0\12\7\21\0\11\5\14\0\3\5\36\4\15\5\2\4\12\7"+
    "\54\4\16\5\14\0\44\4\24\5\10\0\12\7\3\0\3\4\12\7"+
    "\44\4\122\0\3\5\1\0\25\5\4\4\1\5\4\4\3\5\2\4"+
    "\11\0\300\4\47\5\25\0\4\5\u0116\4\2\0\6\4\2\0\46\4"+
    "\2\0\6\4\2\0\10\4\1\0\1\4\1\0\1\4\1\0\1\4"+
    "\1\0\37\4\2\0\65\4\1\0\7\4\1\0\1\4\3\0\3\4"+
    "\1\0\7\4\3\0\4\4\2\0\6\4\4\0\15\4\5\0\3\4"+
    "\1\0\7\4\16\0\5\5\32\0\5\5\20\0\2\4\23\0\1\4"+
    "\13\0\5\5\5\0\6\5\1\0\1\4\15\0\1\4\20\0\15\4"+
    "\3\0\33\4\25\0\15\5\4\0\1\5\3\0\14\5\21\0\1\4"+
    "\4\0\1\4\2\0\12\4\1\0\1\4\3\0\5\4\6\0\1\4"+
    "\1\0\1\4\1\0\1\4\1\0\4\4\1\0\13\4\2\0\4\4"+
    "\5\0\5\4\4\0\1\4\21\0\51\4\u0a77\0\57\4\1\0\57\4"+
    "\1\0\205\4\6\0\4\4\3\5\2\4\14\0\46\4\1\0\1\4"+
    "\5\0\1\4\2\0\70\4\7\0\1\4\17\0\1\5\27\4\11\0"+
    "\7\4\1\0\7\4\1\0\7\4\1\0\7\4\1\0\7\4\1\0"+
    "\7\4\1\0\7\4\1\0\7\4\1\0\40\5\57\0\1\4\u01d5\0"+
    "\3\4\31\0\11\4\6\5\1\0\5\4\2\0\5\4\4\0\126\4"+
    "\2\0\2\5\2\0\3\4\1\0\132\4\1\0\4\4\5\0\51\4"+
    "\3\0\136\4\21\0\33\4\65\0\20\4\u0200\0\u19b6\4\112\0\u51cd\4"+
    "\63\0\u048d\4\103\0\56\4\2\0\u010d\4\3\0\20\4\12\7\2\4"+
    "\24\0\57\4\1\5\4\0\12\5\1\0\31\4\7\0\1\5\120\4"+
    "\2\5\45\0\11\4\2\0\147\4\2\0\4\4\1\0\4\4\14\0"+
    "\13\4\115\0\12\4\1\5\3\4\1\5\4\4\1\5\27\4\5\5"+
    "\20\0\1\4\7\0\64\4\14\0\2\5\62\4\21\5\13\0\12\7"+
    "\6\0\22\5\6\4\3\0\1\4\4\0\12\7\34\4\10\5\2\0"+
    "\27\4\15\5\14\0\35\4\3\0\4\5\57\4\16\5\16\0\1\4"+
    "\12\7\46\0\51\4\16\5\11\0\3\4\1\5\10\4\2\5\2\0"+
    "\12\7\6\0\27\4\3\0\1\4\1\5\4\0\60\4\1\5\1\4"+
    "\3\5\2\4\2\5\5\4\2\5\1\4\1\5\1\4\30\0\3\4"+
    "\2\0\13\4\5\5\2\0\3\4\2\5\12\0\6\4\2\0\6\4"+
    "\2\0\6\4\11\0\7\4\1\0\7\4\221\0\43\4\10\5\1\0"+
    "\2\5\2\0\12\7\6\0\u2ba4\4\14\0\27\4\4\0\61\4\u2104\0"+
    "\u016e\4\2\0\152\4\46\0\7\4\14\0\5\4\5\0\1\4\1\5"+
    "\12\4\1\0\15\4\1\0\5\4\1\0\1\4\1\0\2\4\1\0"+
    "\2\4\1\0\154\4\41\0\u016b\4\22\0\100\4\2\0\66\4\50\0"+
    "\15\4\3\0\20\5\20\0\7\5\14\0\2\4\30\0\3\4\31\0"+
    "\1\4\6\0\5\4\1\0\207\4\2\0\1\5\4\0\1\4\13\0"+
    "\12\7\7\0\32\4\4\0\1\4\1\0\32\4\13\0\131\4\3\0"+
    "\6\4\2\0\6\4\2\0\6\4\2\0\3\4\3\0\2\4\3\0"+
    "\2\4\22\0\3\5\1\0\1\5\2\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\1\1\2\3\3\1\4\1\1\1\5\3\2\1\6"+
    "\1\7\1\10\1\11\1\12\1\13\1\14\14\4\1\15"+
    "\2\4\1\16\1\0\1\1\1\0\1\17\12\0\1\20"+
    "\1\0\1\21\11\0\1\4\1\22\27\4\1\23\24\0"+
    "\7\4\1\24\22\4\1\0\1\23\22\0\4\4\1\25"+
    "\1\4\1\26\3\4\1\27\10\4\1\30\5\4\1\23"+
    "\16\0\1\31\3\0\5\4\1\32\1\33\1\4\1\0"+
    "\6\4\1\34\2\4\1\35\1\36\2\4\5\0\1\37"+
    "\5\0\1\40\5\0\1\41\1\0\1\4\1\42\1\43"+
    "\2\4\1\44\1\0\1\4\1\45\6\4\1\46\1\0"+
    "\1\47\4\0\1\50\4\0\1\51\4\0\5\4\1\0"+
    "\1\4\1\52\1\53\1\4\1\54\1\55\1\4\1\0"+
    "\1\56\6\0\1\57\1\60\1\0\1\61\1\0\5\4"+
    "\1\0\1\62\2\4\1\0\1\63\1\0\1\64\1\0"+
    "\1\65\3\0\1\66\4\4\1\0\2\4\6\0\1\67"+
    "\1\70\2\4\1\0\1\71\1\72\3\0\1\73\1\74"+
    "\1\75\1\4\1\76\1\0\1\77\1\100\1\101\1\4"+
    "\1\0\1\102\4\0\1\103";

  private static int [] zzUnpackAction() {
    int [] result = new int[354];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\51\0\122\0\173\0\51\0\244\0\315\0\315"+
    "\0\366\0\u011f\0\u0148\0\u0171\0\51\0\u019a\0\51\0\51"+
    "\0\u01c3\0\u01ec\0\u0215\0\u023e\0\u0267\0\u0290\0\u02b9\0\u02e2"+
    "\0\u030b\0\u0334\0\u035d\0\u0386\0\u03af\0\u03d8\0\244\0\u0401"+
    "\0\u042a\0\244\0\366\0\366\0\u011f\0\51\0\u0453\0\u047c"+
    "\0\u04a5\0\u04ce\0\u04f7\0\u0520\0\u0549\0\u0572\0\u059b\0\u019a"+
    "\0\51\0\u01c3\0\51\0\u05c4\0\u05ed\0\u0616\0\u063f\0\u0668"+
    "\0\u0691\0\u06ba\0\u06e3\0\u070c\0\u0735\0\244\0\u075e\0\u0787"+
    "\0\u07b0\0\u07d9\0\u0802\0\u082b\0\u0854\0\u087d\0\u08a6\0\u08cf"+
    "\0\u08f8\0\u0921\0\u094a\0\u0973\0\u099c\0\u09c5\0\u09ee\0\u0a17"+
    "\0\u0a40\0\u0a69\0\u0a92\0\u0abb\0\u0ae4\0\u0453\0\u0b0d\0\u0b36"+
    "\0\u0b5f\0\u0b88\0\u0bb1\0\u0bda\0\u0c03\0\u0c2c\0\u0c55\0\u0c7e"+
    "\0\u0ca7\0\u0cd0\0\u0cf9\0\u0d22\0\u0d4b\0\u0d74\0\u0d9d\0\u0dc6"+
    "\0\u0def\0\u0e18\0\u0e41\0\u0e6a\0\u0e93\0\u0ebc\0\u0ee5\0\u0f0e"+
    "\0\u0f37\0\244\0\u0f60\0\u0f89\0\u0fb2\0\u0fdb\0\u1004\0\u102d"+
    "\0\u1056\0\u107f\0\u10a8\0\u10d1\0\u10fa\0\u1123\0\u114c\0\u1175"+
    "\0\u119e\0\u11c7\0\u11f0\0\u1219\0\u1242\0\u0b0d\0\u126b\0\u1294"+
    "\0\u12bd\0\u12e6\0\u130f\0\u1338\0\u1361\0\u138a\0\u13b3\0\u13dc"+
    "\0\u1405\0\u142e\0\u1457\0\u1480\0\u14a9\0\u14d2\0\u14fb\0\u1524"+
    "\0\u154d\0\u1576\0\u159f\0\u15c8\0\244\0\u15f1\0\244\0\u161a"+
    "\0\u1643\0\u166c\0\244\0\u1695\0\u16be\0\u16e7\0\u1710\0\u1739"+
    "\0\u1762\0\u178b\0\u17b4\0\244\0\u17dd\0\u1806\0\u182f\0\u1858"+
    "\0\u1881\0\51\0\u18aa\0\u18d3\0\u18fc\0\u1925\0\u194e\0\u1977"+
    "\0\u19a0\0\u19c9\0\u19f2\0\u1a1b\0\u1a44\0\u1a6d\0\u1a96\0\u1abf"+
    "\0\51\0\u1ae8\0\u1b11\0\u1b3a\0\u1b63\0\u1b8c\0\u1bb5\0\u1bde"+
    "\0\u1c07\0\244\0\244\0\u1c30\0\u1c59\0\u1c82\0\u1cab\0\u1cd4"+
    "\0\u1cfd\0\u1d26\0\u1d4f\0\244\0\u1d78\0\u1da1\0\244\0\244"+
    "\0\u1dca\0\u1df3\0\u1e1c\0\u1e45\0\u1e6e\0\u1e97\0\u1ec0\0\51"+
    "\0\u1ee9\0\u1f12\0\u1f3b\0\u1f64\0\u1f8d\0\51\0\u1fb6\0\u1fdf"+
    "\0\u2008\0\u2031\0\u205a\0\51\0\u2083\0\u20ac\0\244\0\244"+
    "\0\u20d5\0\u20fe\0\u2127\0\u2150\0\u2179\0\244\0\u21a2\0\u21cb"+
    "\0\u21f4\0\u221d\0\u2246\0\u226f\0\244\0\u2298\0\51\0\u22c1"+
    "\0\u22ea\0\u2313\0\u233c\0\51\0\u2365\0\u238e\0\u23b7\0\u23e0"+
    "\0\51\0\u2409\0\u2432\0\u245b\0\u2484\0\u24ad\0\u24d6\0\u24ff"+
    "\0\u2528\0\u2551\0\u257a\0\u25a3\0\244\0\244\0\u25cc\0\244"+
    "\0\244\0\u25f5\0\u261e\0\51\0\u2647\0\u2670\0\u2699\0\u26c2"+
    "\0\u26eb\0\u2714\0\51\0\51\0\u273d\0\51\0\u2766\0\u278f"+
    "\0\u27b8\0\u27e1\0\u280a\0\u2833\0\u285c\0\51\0\u2885\0\u28ae"+
    "\0\u28d7\0\51\0\u2900\0\51\0\u2929\0\51\0\u2952\0\u297b"+
    "\0\u29a4\0\51\0\u29cd\0\u29f6\0\u2a1f\0\u2a48\0\u2a71\0\u2a9a"+
    "\0\u2ac3\0\u2aec\0\u2b15\0\u2b3e\0\u2b67\0\u2b90\0\u2bb9\0\244"+
    "\0\244\0\u2be2\0\u2c0b\0\u2c34\0\244\0\244\0\u2c5d\0\u2c86"+
    "\0\u2caf\0\51\0\51\0\51\0\u2cd8\0\244\0\u2d01\0\51"+
    "\0\51\0\51\0\u2d2a\0\u2d53\0\244\0\u2d7c\0\u2da5\0\u2dce"+
    "\0\u2df7\0\51";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[354];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\4\1\5\1\6\1\2\1\7\1\10"+
    "\1\11\1\12\1\2\1\13\1\6\1\14\1\15\1\16"+
    "\1\17\1\20\1\21\1\22\1\23\1\24\1\25\1\6"+
    "\1\26\1\27\1\30\1\31\1\32\1\33\1\34\1\35"+
    "\1\36\1\37\1\40\1\41\3\6\1\42\1\6\53\0"+
    "\1\5\47\0\1\5\53\0\2\6\1\0\1\6\4\0"+
    "\1\6\7\0\25\6\7\0\1\10\1\43\47\0\1\44"+
    "\41\0\11\45\1\46\1\0\36\45\13\0\1\47\1\50"+
    "\61\0\1\51\3\0\1\52\2\0\1\53\1\0\1\54"+
    "\1\55\1\56\1\0\1\57\6\0\20\60\1\61\30\60"+
    "\23\62\1\63\25\62\24\0\1\64\1\65\3\0\1\66"+
    "\1\0\1\67\1\70\1\0\1\71\1\72\1\73\1\0"+
    "\1\74\12\0\2\6\1\0\1\6\4\0\1\6\7\0"+
    "\1\6\1\75\11\6\1\76\11\6\4\0\2\6\1\0"+
    "\1\6\4\0\1\6\7\0\1\77\5\6\1\100\12\6"+
    "\1\101\3\6\4\0\2\6\1\0\1\6\4\0\1\6"+
    "\7\0\6\6\1\102\16\6\4\0\2\6\1\0\1\6"+
    "\4\0\1\6\7\0\10\6\1\103\14\6\4\0\2\6"+
    "\1\0\1\6\4\0\1\6\7\0\1\104\5\6\1\105"+
    "\1\6\1\106\14\6\4\0\2\6\1\0\1\6\4\0"+
    "\1\6\7\0\11\6\1\107\1\110\3\6\1\111\2\6"+
    "\1\112\3\6\4\0\2\6\1\0\1\6\4\0\1\6"+
    "\7\0\10\6\1\113\14\6\4\0\2\6\1\0\1\6"+
    "\4\0\1\6\7\0\11\6\1\114\13\6\4\0\2\6"+
    "\1\0\1\6\4\0\1\6\7\0\3\6\1\115\4\6"+
    "\1\116\14\6\4\0\2\6\1\0\1\6\4\0\1\6"+
    "\7\0\3\6\1\117\15\6\1\120\3\6\4\0\2\6"+
    "\1\0\1\6\4\0\1\6\7\0\6\6\1\121\1\6"+
    "\1\122\14\6\4\0\2\6\1\0\1\6\4\0\1\6"+
    "\7\0\3\6\1\123\21\6\4\0\2\6\1\0\1\6"+
    "\4\0\1\6\7\0\1\124\24\6\4\0\2\6\1\0"+
    "\1\6\4\0\1\6\7\0\21\6\1\125\3\6\1\126"+
    "\2\0\46\126\14\127\1\130\34\127\45\0\1\131\37\0"+
    "\1\132\51\0\1\133\42\0\1\134\53\0\1\135\1\0"+
    "\1\136\43\0\1\137\45\0\1\140\51\0\1\141\70\0"+
    "\1\142\37\0\1\143\50\0\1\144\51\0\1\145\42\0"+
    "\1\146\53\0\1\147\1\0\1\150\43\0\1\151\45\0"+
    "\1\152\30\0\2\6\1\0\1\6\4\0\1\6\7\0"+
    "\2\6\1\153\22\6\4\0\2\6\1\0\1\6\4\0"+
    "\1\6\7\0\11\6\1\154\13\6\4\0\2\6\1\0"+
    "\1\6\4\0\1\6\7\0\15\6\1\155\7\6\4\0"+
    "\2\6\1\0\1\6\4\0\1\6\7\0\16\6\1\156"+
    "\6\6\4\0\2\6\1\0\1\6\4\0\1\6\7\0"+
    "\5\6\1\157\17\6\4\0\2\6\1\0\1\6\4\0"+
    "\1\6\7\0\17\6\1\160\5\6\4\0\2\6\1\0"+
    "\1\6\4\0\1\6\7\0\2\6\1\161\22\6\4\0"+
    "\2\6\1\0\1\6\4\0\1\6\7\0\1\6\1\162"+
    "\23\6\4\0\2\6\1\0\1\6\4\0\1\6\7\0"+
    "\15\6\1\163\7\6\4\0\2\6\1\0\1\6\4\0"+
    "\1\6\7\0\12\6\1\164\12\6\4\0\2\6\1\0"+
    "\1\6\4\0\1\6\7\0\12\6\1\165\12\6\4\0"+
    "\2\6\1\0\1\6\4\0\1\6\7\0\5\6\1\166"+
    "\17\6\4\0\2\6\1\0\1\6\4\0\1\6\7\0"+
    "\5\6\1\167\17\6\4\0\2\6\1\0\1\6\4\0"+
    "\1\6\7\0\11\6\1\170\13\6\4\0\2\6\1\0"+
    "\1\6\4\0\1\6\7\0\7\6\1\171\15\6\4\0"+
    "\2\6\1\0\1\6\4\0\1\6\7\0\1\6\1\172"+
    "\23\6\4\0\2\6\1\0\1\6\4\0\1\6\7\0"+
    "\24\6\1\173\4\0\2\6\1\0\1\6\4\0\1\6"+
    "\7\0\11\6\1\174\4\6\1\175\6\6\4\0\2\6"+
    "\1\0\1\6\4\0\1\6\7\0\4\6\1\176\20\6"+
    "\4\0\2\6\1\0\1\6\4\0\1\6\7\0\5\6"+
    "\1\177\17\6\4\0\2\6\1\0\1\6\4\0\1\6"+
    "\7\0\17\6\1\200\5\6\4\0\2\6\1\0\1\6"+
    "\4\0\1\6\7\0\4\6\1\201\1\202\17\6\4\0"+
    "\2\6\1\0\1\6\4\0\1\6\7\0\20\6\1\203"+
    "\4\6\4\0\2\6\1\0\1\6\4\0\1\6\7\0"+
    "\10\6\1\204\14\6\14\127\1\205\47\127\1\206\1\130"+
    "\34\127\42\0\1\207\47\0\1\210\42\0\1\211\52\0"+
    "\1\212\44\0\1\213\62\0\1\214\36\0\1\215\63\0"+
    "\1\216\32\0\1\217\64\0\1\220\47\0\1\221\44\0"+
    "\1\222\46\0\1\223\52\0\1\224\44\0\1\225\62\0"+
    "\1\226\36\0\1\227\63\0\1\230\10\0\2\6\1\0"+
    "\1\6\4\0\1\6\7\0\3\6\1\231\21\6\4\0"+
    "\2\6\1\0\1\6\4\0\1\6\7\0\1\232\24\6"+
    "\4\0\2\6\1\0\1\6\4\0\1\6\7\0\1\233"+
    "\24\6\4\0\2\6\1\0\1\6\4\0\1\6\7\0"+
    "\5\6\1\234\17\6\4\0\2\6\1\0\1\6\4\0"+
    "\1\6\7\0\22\6\1\235\2\6\4\0\2\6\1\0"+
    "\1\6\4\0\1\6\7\0\10\6\1\236\14\6\4\0"+
    "\2\6\1\0\1\6\4\0\1\6\7\0\3\6\1\237"+
    "\21\6\4\0\2\6\1\0\1\6\4\0\1\6\7\0"+
    "\5\6\1\240\17\6\4\0\2\6\1\0\1\6\4\0"+
    "\1\6\7\0\22\6\1\241\2\6\4\0\2\6\1\0"+
    "\1\6\4\0\1\6\7\0\1\242\24\6\4\0\2\6"+
    "\1\0\1\6\4\0\1\6\7\0\3\6\1\243\21\6"+
    "\4\0\2\6\1\0\1\6\4\0\1\6\7\0\3\6"+
    "\1\244\21\6\4\0\2\6\1\0\1\6\4\0\1\6"+
    "\7\0\5\6\1\245\17\6\4\0\2\6\1\0\1\6"+
    "\4\0\1\6\7\0\1\246\24\6\4\0\2\6\1\0"+
    "\1\6\4\0\1\6\7\0\14\6\1\247\10\6\4\0"+
    "\2\6\1\0\1\6\4\0\1\6\7\0\4\6\1\250"+
    "\20\6\4\0\2\6\1\0\1\6\4\0\1\6\7\0"+
    "\5\6\1\251\17\6\4\0\2\6\1\0\1\6\4\0"+
    "\1\6\7\0\3\6\1\252\21\6\4\0\2\6\1\0"+
    "\1\6\4\0\1\6\7\0\20\6\1\253\4\6\4\0"+
    "\2\6\1\0\1\6\4\0\1\6\7\0\3\6\1\254"+
    "\21\6\4\0\2\6\1\0\1\6\4\0\1\6\7\0"+
    "\10\6\1\255\14\6\4\0\2\6\1\0\1\6\4\0"+
    "\1\6\7\0\13\6\1\256\11\6\4\0\2\6\1\0"+
    "\1\6\4\0\1\6\7\0\3\6\1\257\21\6\4\0"+
    "\2\6\1\0\1\6\4\0\1\6\7\0\5\6\1\260"+
    "\17\6\4\0\2\6\1\0\1\6\4\0\1\6\7\0"+
    "\11\6\1\261\13\6\13\127\1\262\1\205\34\127\31\0"+
    "\1\263\50\0\1\264\43\0\1\265\55\0\1\266\46\0"+
    "\1\267\55\0\1\270\43\0\1\271\52\0\1\272\46\0"+
    "\1\273\52\0\1\274\50\0\1\275\50\0\1\276\43\0"+
    "\1\277\55\0\1\300\46\0\1\301\55\0\1\302\43\0"+
    "\1\303\52\0\1\304\23\0\2\6\1\0\1\6\4\0"+
    "\1\6\7\0\4\6\1\305\20\6\4\0\2\6\1\0"+
    "\1\6\4\0\1\6\7\0\1\6\1\306\23\6\4\0"+
    "\2\6\1\0\1\6\4\0\1\6\7\0\1\6\1\307"+
    "\23\6\4\0\2\6\1\0\1\6\4\0\1\6\7\0"+
    "\1\310\24\6\4\0\2\6\1\0\1\6\4\0\1\6"+
    "\7\0\4\6\1\311\20\6\4\0\2\6\1\0\1\6"+
    "\4\0\1\6\7\0\3\6\1\312\21\6\4\0\2\6"+
    "\1\0\1\6\4\0\1\6\7\0\3\6\1\313\21\6"+
    "\4\0\2\6\1\0\1\6\4\0\1\6\7\0\3\6"+
    "\1\314\21\6\4\0\2\6\1\315\1\6\4\0\1\6"+
    "\7\0\25\6\4\0\2\6\1\0\1\6\4\0\1\6"+
    "\7\0\6\6\1\316\16\6\4\0\2\6\1\0\1\6"+
    "\4\0\1\6\7\0\6\6\1\317\16\6\4\0\2\6"+
    "\1\0\1\6\4\0\1\6\7\0\4\6\1\320\20\6"+
    "\4\0\2\6\1\0\1\6\4\0\1\6\7\0\1\321"+
    "\24\6\4\0\2\6\1\0\1\6\4\0\1\6\7\0"+
    "\4\6\1\322\3\6\1\323\14\6\4\0\2\6\1\0"+
    "\1\6\4\0\1\6\7\0\4\6\1\324\20\6\4\0"+
    "\2\6\1\0\1\6\4\0\1\6\7\0\1\325\24\6"+
    "\4\0\2\6\1\0\1\6\4\0\1\6\7\0\12\6"+
    "\1\326\12\6\4\0\2\6\1\0\1\6\4\0\1\6"+
    "\7\0\10\6\1\327\14\6\4\0\2\6\1\0\1\6"+
    "\4\0\1\6\7\0\11\6\1\330\13\6\4\0\2\6"+
    "\1\0\1\6\4\0\1\6\7\0\6\6\1\331\16\6"+
    "\4\0\2\6\1\0\1\6\4\0\1\6\7\0\5\6"+
    "\1\332\17\6\24\0\1\333\53\0\1\334\53\0\1\335"+
    "\46\0\1\336\3\0\1\337\36\0\1\340\64\0\1\341"+
    "\47\0\1\342\45\0\1\343\46\0\1\344\44\0\1\345"+
    "\53\0\1\346\53\0\1\347\50\0\1\350\46\0\1\351"+
    "\3\0\1\352\52\0\1\353\47\0\1\354\45\0\1\355"+
    "\22\0\2\6\1\0\1\6\4\0\1\6\7\0\5\6"+
    "\1\356\17\6\4\0\2\6\1\0\1\6\4\0\1\6"+
    "\7\0\3\6\1\357\21\6\4\0\2\6\1\0\1\6"+
    "\4\0\1\6\7\0\3\6\1\360\21\6\4\0\2\6"+
    "\1\0\1\6\4\0\1\6\7\0\1\6\1\361\23\6"+
    "\4\0\2\6\1\0\1\6\4\0\1\6\7\0\10\6"+
    "\1\362\14\6\4\0\2\6\1\0\1\6\4\0\1\6"+
    "\7\0\11\6\1\363\13\6\30\0\1\364\24\0\2\6"+
    "\1\0\1\6\4\0\1\6\7\0\11\6\1\365\13\6"+
    "\4\0\2\6\1\0\1\6\4\0\1\6\7\0\4\6"+
    "\1\366\20\6\4\0\2\6\1\0\1\6\4\0\1\6"+
    "\7\0\10\6\1\237\14\6\4\0\2\6\1\0\1\6"+
    "\4\0\1\6\7\0\5\6\1\367\17\6\4\0\2\6"+
    "\1\0\1\6\4\0\1\6\7\0\3\6\1\370\21\6"+
    "\4\0\2\6\1\0\1\6\4\0\1\6\7\0\11\6"+
    "\1\371\13\6\4\0\2\6\1\0\1\6\4\0\1\6"+
    "\7\0\7\6\1\372\15\6\4\0\2\6\1\0\1\6"+
    "\4\0\1\6\7\0\5\6\1\373\17\6\4\0\2\6"+
    "\1\0\1\6\4\0\1\6\7\0\13\6\1\374\11\6"+
    "\4\0\2\6\1\0\1\6\4\0\1\6\7\0\10\6"+
    "\1\375\14\6\25\0\1\376\45\0\1\377\56\0\1\u0100"+
    "\47\0\1\u0101\56\0\1\u0102\44\0\1\u0103\41\0\1\u0104"+
    "\65\0\1\u0105\42\0\1\u0106\44\0\1\u0107\60\0\1\u0108"+
    "\43\0\1\u0109\47\0\1\u010a\56\0\1\u010b\44\0\1\u010c"+
    "\56\0\1\u010d\15\0\2\6\1\0\1\6\4\0\1\6"+
    "\7\0\6\6\1\u010e\16\6\4\0\2\6\1\0\1\6"+
    "\4\0\1\6\7\0\10\6\1\u010f\14\6\4\0\2\6"+
    "\1\0\1\6\4\0\1\6\7\0\11\6\1\u0110\13\6"+
    "\4\0\2\6\1\0\1\6\4\0\1\6\7\0\1\u0111"+
    "\16\6\1\u0112\5\6\34\0\1\u0113\20\0\2\6\1\0"+
    "\1\6\4\0\1\6\7\0\6\6\1\u0114\16\6\4\0"+
    "\2\6\1\0\1\6\4\0\1\6\7\0\6\6\1\u0115"+
    "\16\6\4\0\2\6\1\0\1\6\4\0\1\6\7\0"+
    "\16\6\1\u0116\6\6\4\0\2\6\1\0\1\6\4\0"+
    "\1\6\7\0\10\6\1\u0117\14\6\4\0\2\6\1\0"+
    "\1\6\4\0\1\6\7\0\6\6\1\u0118\16\6\4\0"+
    "\2\6\1\0\1\6\4\0\1\6\7\0\3\6\1\u0119"+
    "\21\6\4\0\2\6\1\0\1\6\4\0\1\6\7\0"+
    "\6\6\1\u011a\16\6\34\0\1\u011b\36\0\1\u011c\70\0"+
    "\1\u011d\42\0\1\u011e\43\0\1\u011f\53\0\1\u0120\50\0"+
    "\1\u0121\52\0\1\u0122\46\0\1\u0123\60\0\1\u0124\42\0"+
    "\1\u0125\43\0\1\u0126\53\0\1\u0127\22\0\2\6\1\0"+
    "\1\6\4\0\1\6\7\0\4\6\1\u0128\20\6\4\0"+
    "\2\6\1\0\1\6\4\0\1\6\7\0\13\6\1\u0129"+
    "\11\6\4\0\2\6\1\0\1\6\4\0\1\6\7\0"+
    "\12\6\1\u012a\12\6\4\0\2\6\1\0\1\6\4\0"+
    "\1\6\7\0\11\6\1\u012b\13\6\4\0\2\6\1\0"+
    "\1\6\4\0\1\6\7\0\1\u012c\24\6\26\0\1\u012d"+
    "\26\0\2\6\1\0\1\6\4\0\1\6\5\0\1\u012e"+
    "\1\0\25\6\4\0\2\6\1\0\1\6\4\0\1\6"+
    "\7\0\13\6\1\u012f\11\6\4\0\2\6\1\0\1\6"+
    "\4\0\1\6\7\0\5\6\1\u0130\17\6\37\0\1\u0131"+
    "\33\0\1\u0132\65\0\1\u0133\33\0\1\u0134\57\0\1\u0135"+
    "\47\0\1\u0136\57\0\1\u0137\50\0\1\u0138\42\0\1\u0139"+
    "\23\0\2\6\1\0\1\6\4\0\1\6\5\0\1\u013a"+
    "\1\0\25\6\4\0\2\6\1\0\1\6\4\0\1\6"+
    "\7\0\1\u013b\24\6\4\0\2\6\1\0\1\6\4\0"+
    "\1\6\7\0\1\u013c\24\6\4\0\2\6\1\0\1\6"+
    "\4\0\1\6\7\0\1\u013d\24\6\4\0\2\6\1\0"+
    "\1\6\4\0\1\6\7\0\11\6\1\u013e\13\6\30\0"+
    "\1\u013f\24\0\2\6\1\0\1\6\4\0\1\6\7\0"+
    "\3\6\1\u0140\21\6\4\0\2\6\1\0\1\6\4\0"+
    "\1\6\7\0\3\6\1\u0141\21\6\24\0\1\u0142\53\0"+
    "\1\u0143\50\0\1\u0144\45\0\1\u0145\53\0\1\u0146\50\0"+
    "\1\u0147\25\0\2\6\1\0\1\6\4\0\1\6\7\0"+
    "\6\6\1\u0148\16\6\4\0\2\6\1\0\1\6\4\0"+
    "\1\6\7\0\6\6\1\u0149\16\6\4\0\2\6\1\0"+
    "\1\6\4\0\1\6\7\0\12\6\1\u014a\12\6\4\0"+
    "\2\6\1\0\1\6\4\0\1\6\7\0\6\6\1\u014b"+
    "\16\6\27\0\1\u014c\25\0\2\6\1\0\1\6\4\0"+
    "\1\6\7\0\4\6\1\u014d\20\6\4\0\2\6\1\0"+
    "\1\6\4\0\1\6\7\0\20\6\1\u014e\4\6\32\0"+
    "\1\u014f\46\0\1\u0150\64\0\1\u0151\36\0\1\u0152\46\0"+
    "\1\u0153\64\0\1\u0154\10\0\2\6\1\0\1\6\4\0"+
    "\1\6\7\0\1\u0155\24\6\4\0\2\6\1\0\1\6"+
    "\4\0\1\6\7\0\16\6\1\u0156\6\6\37\0\1\u0157"+
    "\33\0\1\u0158\50\0\1\u0159\50\0\1\u015a\32\0\2\6"+
    "\1\0\1\6\4\0\1\6\7\0\6\6\1\u015b\16\6"+
    "\45\0\1\u015c\7\0\2\6\1\0\1\6\4\0\1\6"+
    "\7\0\16\6\1\u015d\6\6\36\0\1\u015e\50\0\1\u015f"+
    "\36\0\1\u0160\53\0\1\u0161\56\0\1\u0162\13\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[11808];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\1\1\11\2\1\1\11\7\1\1\11\1\1\2\11"+
    "\22\1\1\0\1\1\1\0\1\11\12\0\1\11\1\0"+
    "\1\11\11\0\32\1\24\0\32\1\1\0\1\1\22\0"+
    "\31\1\1\11\16\0\1\11\3\0\10\1\1\0\15\1"+
    "\5\0\1\11\5\0\1\11\5\0\1\11\1\0\6\1"+
    "\1\0\11\1\1\0\1\11\4\0\1\11\4\0\1\11"+
    "\4\0\5\1\1\0\7\1\1\0\1\11\6\0\2\11"+
    "\1\0\1\11\1\0\5\1\1\0\1\11\2\1\1\0"+
    "\1\11\1\0\1\11\1\0\1\11\3\0\1\11\4\1"+
    "\1\0\2\1\6\0\4\1\1\0\2\1\3\0\3\11"+
    "\2\1\1\0\3\11\1\1\1\0\1\1\4\0\1\11";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[354];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;


  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public LexGxml(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  public LexGxml(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 2292) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzCurrentPos*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = zzReader.read(zzBuffer, zzEndRead,
                                            zzBuffer.length-zzEndRead);

    if (numRead > 0) {
      zzEndRead+= numRead;
      return false;
    }
    // unlikely but not impossible: read 0 characters, but not at end of stream    
    if (numRead == 0) {
      int c = zzReader.read();
      if (c == -1) {
        return true;
      } else {
        zzBuffer[zzEndRead++] = (char) c;
        return false;
      }     
    }

	// numRead < 0
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      yychar+= zzMarkedPosL-zzStartRead;

      boolean zzR = false;
      for (zzCurrentPosL = zzStartRead; zzCurrentPosL < zzMarkedPosL;
                                                             zzCurrentPosL++) {
        switch (zzBufferL[zzCurrentPosL]) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn++;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL[zzCurrentPosL++];
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL[zzCurrentPosL++];
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 5: 
          { return new Symbol(sym.int_literal, new token(yycolumn, yyline, yytext()));
          }
        case 68: break;
        case 56: 
          { return new Symbol(sym.referencia, new token(yycolumn, yyline, yytext()));
          }
        case 69: break;
        case 55: 
          { System.out.println("tk:"+yytext()); return new Symbol(sym.multimediaA2, new token(yycolumn, yyline, yytext()));
          }
        case 70: break;
        case 48: 
          { System.out.println("tk:"+yytext()); return new Symbol(sym.controlA1, new token(yycolumn, yyline, yytext()));
          }
        case 71: break;
        case 1: 
          { return new Symbol(sym.double_literal, new token(yycolumn, yyline, yytext()));
          }
        case 72: break;
        case 61: 
          { System.out.println("tk:"+yytext()); return new Symbol(sym.listadatosA1, new token(yycolumn, yyline, yytext()));
          }
        case 73: break;
        case 46: 
          { System.out.println("tk:"+yytext()); return new Symbol(sym.enviarF1, new token(yycolumn, yyline, yytext()));
          }
        case 74: break;
        case 40: 
          { System.out.println("tk:"+yytext()); return new Symbol(sym.botonF1, new token(yycolumn, yyline, yytext()));
          }
        case 75: break;
        case 31: 
          { System.out.println("tk:"+yytext()); return new Symbol(sym.datoF1, new token(yycolumn, yyline, yytext()));
          }
        case 76: break;
        case 52: 
          { System.out.println("tk:"+yytext()); return new Symbol(sym.defectoF1, new token(yycolumn, yyline, yytext()));
          }
        case 77: break;
        case 7: 
          { return new Symbol(sym.igual, new token(yycolumn, yyline, yytext()));
          }
        case 78: break;
        case 22: 
          { return new Symbol(sym.tipo, new token(yycolumn, yyline, yytext()));
          }
        case 79: break;
        case 59: 
          { System.out.println("tk:"+yytext()); return new Symbol(sym.multimediaA1, new token(yycolumn, yyline, yytext()));
          }
        case 80: break;
        case 23: 
          { return new Symbol(sym.alto, new token(yycolumn, yyline, yytext()));
          }
        case 81: break;
        case 15: 
          { return new Symbol(sym.string_literal, new token(yycolumn, yyline, yytext()));
          }
        case 82: break;
        case 50: 
          { System.out.println("tk:"+yytext()); return new Symbol(sym.ventanaF1, new token(yycolumn, yyline, yytext()));
          }
        case 83: break;
        case 17: 
          { System.out.println("tk:"+yytext()); return new Symbol(sym.explicit, new token(yycolumn, yyline, yytext()));
          }
        case 84: break;
        case 12: 
          { System.out.println("tk:"+yytext()); return new Symbol(sym.menq, new token(yycolumn, yyline, yytext()));
          }
        case 85: break;
        case 3: 
          { /* ignorar */
          }
        case 86: break;
        case 64: 
          { System.out.println("tk:"+yytext()); return new Symbol(sym.contenedorF1, new token(yycolumn, yyline, yytext()));
          }
        case 87: break;
        case 4: 
          { return new Symbol(sym.ID, new token(yycolumn, yyline, yytext()));
          }
        case 88: break;
        case 9: 
          { return new Symbol(sym.clla, new token(yycolumn, yyline, yytext()));
          }
        case 89: break;
        case 67: 
          { return new Symbol(sym.autorepro, new token(yycolumn, yyline, yytext()));
          }
        case 90: break;
        case 54: 
          { return new Symbol(sym.importarF1, new token(yycolumn, yyline, yytext()));
          }
        case 91: break;
        case 44: 
          { return new Symbol(sym.cursiva, new token(yycolumn, yyline, yytext()));
          }
        case 92: break;
        case 37: 
          { System.out.println("tk:"+yytext()); return new Symbol(sym.enviarA2, new token(yycolumn, yyline, yytext()));
          }
        case 93: break;
        case 30: 
          { System.out.println("tk:"+yytext()); return new Symbol(sym.botonA2, new token(yycolumn, yyline, yytext()));
          }
        case 94: break;
        case 38: 
          { return new Symbol(sym.fuente, new token(yycolumn, yyline, yytext()));
          }
        case 95: break;
        case 35: 
          { return new Symbol(sym.maximo, new token(yycolumn, yyline, yytext()));
          }
        case 96: break;
        case 36: 
          { return new Symbol(sym.accion, new token(yycolumn, yyline, yytext()));
          }
        case 97: break;
        case 24: 
          { System.out.println("tk:"+yytext()); return new Symbol(sym.datoA2, new token(yycolumn, yyline, yytext()));
          }
        case 98: break;
        case 45: 
          { System.out.println("tk:"+yytext()); return new Symbol(sym.defectoA2, new token(yycolumn, yyline, yytext()));
          }
        case 99: break;
        case 66: 
          { return new Symbol(sym.accionini, new token(yycolumn, yyline, yytext()));
          }
        case 100: break;
        case 39: 
          { System.out.println("tk:"+yytext()); return new Symbol(sym.textoF1, new token(yycolumn, yyline, yytext()));
          }
        case 101: break;
        case 10: 
          { return new Symbol(sym.pyc, new token(yycolumn, yyline, yytext()));
          }
        case 102: break;
        case 41: 
          { System.out.println("tk:"+yytext()); return new Symbol(sym.enviarA1, new token(yycolumn, yyline, yytext()));
          }
        case 103: break;
        case 33: 
          { System.out.println("tk:"+yytext()); return new Symbol(sym.botonA1, new token(yycolumn, yyline, yytext()));
          }
        case 104: break;
        case 51: 
          { System.out.println("tk:"+yytext()); return new Symbol(sym.controlF1, new token(yycolumn, yyline, yytext()));
          }
        case 105: break;
        case 14: 
          { return new Symbol(sym.y, new token(yycolumn, yyline, yytext()));
          }
        case 106: break;
        case 25: 
          { System.out.println("tk:"+yytext()); return new Symbol(sym.datoA1, new token(yycolumn, yyline, yytext()));
          }
        case 107: break;
        case 49: 
          { System.out.println("tk:"+yytext()); return new Symbol(sym.defectoA1, new token(yycolumn, yyline, yytext()));
          }
        case 108: break;
        case 16: 
          { System.out.println("Yk:"+yytext()); return new Symbol(sym.event, new token(yycolumn, yyline, yytext()));
          }
        case 109: break;
        case 34: 
          { return new Symbol(sym.minimo, new token(yycolumn, yyline, yytext()));
          }
        case 110: break;
        case 6: 
          { return new Symbol(sym.div, new token(yycolumn, yyline, yytext()));
          }
        case 111: break;
        case 57: 
          { System.out.println("tk:"+yytext()); return new Symbol(sym.contenedorA2, new token(yycolumn, yyline, yytext()));
          }
        case 112: break;
        case 65: 
          { System.out.println("tk:"+yytext()); return new Symbol(sym.listadatosF1, new token(yycolumn, yyline, yytext()));
          }
        case 113: break;
        case 53: 
          { return new Symbol(sym.importarA2, new token(yycolumn, yyline, yytext()));
          }
        case 114: break;
        case 8: 
          { return new Symbol(sym.alla, new token(yycolumn, yyline, yytext()));
          }
        case 115: break;
        case 62: 
          { return new Symbol(sym.accionfin, new token(yycolumn, yyline, yytext()));
          }
        case 116: break;
        case 20: 
          { return new Symbol(sym.tam, new token(yycolumn, yyline, yytext()));
          }
        case 117: break;
        case 47: 
          { System.out.println("tk:"+yytext()); return new Symbol(sym.ventanaA1, new token(yycolumn, yyline, yytext()));
          }
        case 118: break;
        case 13: 
          { return new Symbol(sym.x, new token(yycolumn, yyline, yytext()));
          }
        case 119: break;
        case 26: 
          { System.out.println("tk:"+yytext()); return new Symbol(sym.textoA2, new token(yycolumn, yyline, yytext()));
          }
        case 120: break;
        case 63: 
          { System.out.println("tk:"+yytext()); return new Symbol(sym.multimediaF1, new token(yycolumn, yyline, yytext()));
          }
        case 121: break;
        case 11: 
          { System.out.println("tk:"+yytext()); return new Symbol(sym.mayq, new token(yycolumn, yyline, yytext()));
          }
        case 122: break;
        case 60: 
          { System.out.println("tk:"+yytext()); return new Symbol(sym.contenedorA1, new token(yycolumn, yyline, yytext()));
          }
        case 123: break;
        case 21: 
          { return new Symbol(sym.path, new token(yycolumn, yyline, yytext()));
          }
        case 124: break;
        case 27: 
          { return new Symbol(sym.ancho, new token(yycolumn, yyline, yytext()));
          }
        case 125: break;
        case 43: 
          { System.out.println("tk:"+yytext()); return new Symbol(sym.controlA2, new token(yycolumn, yyline, yytext()));
          }
        case 126: break;
        case 42: 
          { return new Symbol(sym.negrita, new token(yycolumn, yyline, yytext()));
          }
        case 127: break;
        case 28: 
          { return new Symbol(sym.color, new token(yycolumn, yyline, yytext()));
          }
        case 128: break;
        case 58: 
          { System.out.println("tk:"+yytext()); return new Symbol(sym.listadatosA2, new token(yycolumn, yyline, yytext()));
          }
        case 129: break;
        case 32: 
          { System.out.println("tk:"+yytext()); return new Symbol(sym.textoA1, new token(yycolumn, yyline, yytext()));
          }
        case 130: break;
        case 2: 
          { System.err.println(yyline+","+yycolumn+"=["+yytext()+"],"+yychar);
          }
        case 131: break;
        case 29: 
          { return new Symbol(sym.borde, new token(yycolumn, yyline, yytext()));
          }
        case 132: break;
        case 18: 
          { return new Symbol(sym.id, new token(yycolumn, yyline, yytext()));
          }
        case 133: break;
        case 19: 
          { 
          }
        case 134: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            zzDoEOF();
              { return new java_cup.runtime.Symbol(sym.EOF); }
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
