
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Fri Feb 15 20:56:31 CST 2019
//----------------------------------------------------

package Analizadores.Gxml;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int listadatosA1 = 56;
  public static final int contenedorF2 = 11;
  public static final int contenedorF1 = 10;
  public static final int multimediaA2 = 63;
  public static final int ancho = 17;
  public static final int multimediaA1 = 62;
  public static final int alla = 35;
  public static final int maximo = 25;
  public static final int accion = 27;
  public static final int datoA2 = 51;
  public static final int datoA1 = 50;
  public static final int video = 30;
  public static final int controlA2 = 48;
  public static final int controlA1 = 47;
  public static final int imagen = 31;
  public static final int multimedia = 12;
  public static final int defectoF1 = 55;
  public static final int igual = 41;
  public static final int enviarA2 = 60;
  public static final int importarA2 = 3;
  public static final int enviarA1 = 59;
  public static final int importarA1 = 2;
  public static final int alto = 16;
  public static final int ventanaF1 = 7;
  public static final int listadatosF1 = 58;
  public static final int multimediaF1 = 64;
  public static final int fuente = 18;
  public static final int ID = 34;
  public static final int datoF1 = 52;
  public static final int EOF = 0;
  public static final int controlF1 = 49;
  public static final int pyc = 37;
  public static final int nombre = 14;
  public static final int referencia = 28;
  public static final int error = 1;
  public static final int color = 20;
  public static final int textoA2 = 45;
  public static final int importarF2 = 5;
  public static final int enviarF1 = 61;
  public static final int textoA1 = 44;
  public static final int explicit = 38;
  public static final int importarF1 = 4;
  public static final int contenedorA2 = 9;
  public static final int contenedorA1 = 8;
  public static final int id = 15;
  public static final int y = 22;
  public static final int x = 21;
  public static final int tipo = 13;
  public static final int tam = 19;
  public static final int minimo = 26;
  public static final int path = 32;
  public static final int string_literal = 40;
  public static final int defectoA2 = 54;
  public static final int defectoA1 = 53;
  public static final int mayq = 43;
  public static final int clla = 36;
  public static final int div = 39;
  public static final int musica = 29;
  public static final int cursiva = 24;
  public static final int menq = 42;
  public static final int ventanaA1 = 6;
  public static final int negrita = 23;
  public static final int autorepro = 33;
  public static final int textoF1 = 46;
  public static final int listadatosA2 = 57;
}

