
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Feb 21 19:38:23 CST 2019
//----------------------------------------------------

package Analizadores.Gxml;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int listadatosA1 = 51;
  public static final int contenedorF1 = 8;
  public static final int multimediaA2 = 58;
  public static final int ancho = 13;
  public static final int multimediaA1 = 57;
  public static final int alla = 30;
  public static final int maximo = 21;
  public static final int accionfin = 25;
  public static final int accion = 23;
  public static final int datoA2 = 46;
  public static final int datoA1 = 45;
  public static final int controlA2 = 43;
  public static final int controlA1 = 42;
  public static final int accionini = 24;
  public static final int defectoF1 = 50;
  public static final int igual = 36;
  public static final int enviarA2 = 55;
  public static final int importarA2 = 2;
  public static final int enviarA1 = 54;
  public static final int botonF1 = 67;
  public static final int alto = 12;
  public static final int ventanaF1 = 5;
  public static final int listadatosF1 = 53;
  public static final int multimediaF1 = 59;
  public static final int fuente = 14;
  public static final int ID = 29;
  public static final int datoF1 = 47;
  public static final int EOF = 0;
  public static final int controlF1 = 44;
  public static final int pyc = 32;
  public static final int nombre = 10;
  public static final int referencia = 26;
  public static final int error = 1;
  public static final int color = 16;
  public static final int textoA2 = 40;
  public static final int enviarF1 = 56;
  public static final int textoA1 = 39;
  public static final int explicit = 33;
  public static final int importarF1 = 3;
  public static final int double_literal = 61;
  public static final int contenedorA2 = 7;
  public static final int contenedorA1 = 6;
  public static final int id = 11;
  public static final int y = 18;
  public static final int int_literal = 60;
  public static final int x = 17;
  public static final int tipo = 9;
  public static final int tam = 15;
  public static final int minimo = 22;
  public static final int path = 27;
  public static final int string_literal = 35;
  public static final int defectoA2 = 49;
  public static final int defectoA1 = 48;
  public static final int mayq = 38;
  public static final int borde = 63;
  public static final int clla = 31;
  public static final int botonA2 = 66;
  public static final int botonA1 = 65;
  public static final int div = 34;
  public static final int cursiva = 20;
  public static final int bool_literal = 62;
  public static final int menq = 37;
  public static final int ventanaA1 = 4;
  public static final int negrita = 19;
  public static final int autorepro = 28;
  public static final int event = 64;
  public static final int textoF1 = 41;
  public static final int listadatosA2 = 52;
}

