
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Feb 18 11:10:57 CST 2019
//----------------------------------------------------

package Analizadores.Script;

import java_cup.runtime.*;
import java.util.*;
import Estructuras.Nodo;

/** CUP v0.11a beta 20060608 generated parser.
  * @version Mon Feb 18 11:10:57 CST 2019
  */
public class SintacticoScript extends java_cup.runtime.lr_parser {

  /** Default constructor. */
  public SintacticoScript() {super();}

  /** Constructor which sets the default scanner. */
  public SintacticoScript(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public SintacticoScript(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\002\000\002\002\004\000\002\002\003" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\004\000\004\072\004\001\002\000\004\002\000\001" +
    "\002\000\004\002\006\001\002\000\004\002\001\001\002" +
    "" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\004\000\004\002\004\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$SintacticoScript$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$SintacticoScript$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$SintacticoScript$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 0;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}



    /**
     * Método al que se llama para crear un nuevo nodo
     **/ 
    public Nodo crearNodo(String nombre,String valor,int linea,int columna){
        Nodo nuevo = new Nodo(nombre,valor,linea,columna,action_obj.Index);
        action_obj.Index++;
        return nuevo;
    }
    /**
     * Método al que se llama automáticamente ante algún error sintactico.
     **/ 
    public void syntax_error(Symbol s){ 
        System.out.println("Error Sintáctico en la Línea " + (s.left) +
        " Columna "+s.right+ ". No se esperaba este componente: " +s.value+"."); 
    } 

    /**
     * Método al que se llama automáticamente ante algún error sintáctico 
     * en el que ya no es posible una recuperación de errores.
     **/ 
    public void unrecovered_syntax_error(Symbol s) throws java.lang.Exception{ 
        System.out.println("Error síntactico irrecuperable en la Línea " + 
        (s.left)+ " Columna "+s.right+". Componente " + s.value + 
        " no reconocido."); 
    }  

}

/** Cup generated class to encapsulate user supplied action code.*/
class CUP$SintacticoScript$actions {


    //se declaran variables globales etc.
        public int Index=1;

  private final SintacticoScript parser;

  /** Constructor */
  CUP$SintacticoScript$actions(SintacticoScript parser) {
    this.parser = parser;
  }

  /** Method with the actual generated action code. */
  public final java_cup.runtime.Symbol CUP$SintacticoScript$do_action(
    int                        CUP$SintacticoScript$act_num,
    java_cup.runtime.lr_parser CUP$SintacticoScript$parser,
    java.util.Stack            CUP$SintacticoScript$stack,
    int                        CUP$SintacticoScript$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$SintacticoScript$result;

      /* select the action based on the action number */
      switch (CUP$SintacticoScript$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // INICIO ::= string_literal 
            {
              Nodo RESULT =null;

              CUP$SintacticoScript$result = parser.getSymbolFactory().newSymbol("INICIO",0, ((java_cup.runtime.Symbol)CUP$SintacticoScript$stack.peek()), ((java_cup.runtime.Symbol)CUP$SintacticoScript$stack.peek()), RESULT);
            }
          return CUP$SintacticoScript$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // $START ::= INICIO EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$SintacticoScript$stack.elementAt(CUP$SintacticoScript$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$SintacticoScript$stack.elementAt(CUP$SintacticoScript$top-1)).right;
		Nodo start_val = (Nodo)((java_cup.runtime.Symbol) CUP$SintacticoScript$stack.elementAt(CUP$SintacticoScript$top-1)).value;
		RESULT = start_val;
              CUP$SintacticoScript$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$SintacticoScript$stack.elementAt(CUP$SintacticoScript$top-1)), ((java_cup.runtime.Symbol)CUP$SintacticoScript$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$SintacticoScript$parser.done_parsing();
          return CUP$SintacticoScript$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number found in internal parse table");

        }
    }
}

