
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Mar 13 00:49:28 CST 2019
//----------------------------------------------------

package Analizadores.Script;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int creartexto = 68;
  public static final int meniq = 14;
  public static final int menos = 7;
  public static final int funcion = 33;
  public static final int pto = 48;
  public static final int nulo = 80;
  public static final int reduce = 40;
  public static final int alla = 53;
  public static final int string_literal = 57;
  public static final int importar = 25;
  public static final int asigmen = 3;
  public static final int clla = 54;
  public static final int descendente = 34;
  public static final int acorch = 55;
  public static final int selecciona = 27;
  public static final int div = 9;
  public static final int add = 11;
  public static final int dspts = 49;
  public static final int obtenerpornombre = 65;
  public static final int mas = 6;
  public static final int menq = 13;
  public static final int undefined = 81;
  public static final int map = 45;
  public static final int imprimir = 24;
  public static final int detener = 26;
  public static final int sino = 32;
  public static final int trn = 22;
  public static final int todos = 41;
  public static final int dif = 18;
  public static final int crearcontenedor = 67;
  public static final int maximo = 38;
  public static final int caso = 28;
  public static final int pyc = 46;
  public static final int ig_ig = 17;
  public static final int int_literal = 58;
  public static final int crearventana = 66;
  public static final int alguno = 42;
  public static final int leergxml = 62;
  public static final int or = 20;
  public static final int alclic = 77;
  public static final int asigpor = 4;
  public static final int invertir = 37;
  public static final int crearreproductor = 75;
  public static final int creararraydesdearchivo = 36;
  public static final int ccorch = 56;
  public static final int alcerrar = 79;
  public static final int minimo = 39;
  public static final int mayiq = 16;
  public static final int ascendente = 35;
  public static final int mayq = 15;
  public static final int and = 19;
  public static final int retornar = 30;
  public static final int alcargar = 78;
  public static final int crearboton = 73;
  public static final int iden = 61;
  public static final int EOF = 0;
  public static final int apar = 51;
  public static final int obtenerporid = 64;
  public static final int double_literal = 60;
  public static final int cpar = 52;
  public static final int asigdiv = 5;
  public static final int crearimagen = 74;
  public static final int crearareatexto = 70;
  public static final int error = 1;
  public static final int asigmas = 2;
  public static final int buscar = 44;
  public static final int si = 31;
  public static final int crearvideo = 76;
  public static final int creardesplegable = 72;
  public static final int crearcajatexto = 69;
  public static final int defecto = 29;
  public static final int pot = 10;
  public static final int crearcontrolnumerico = 71;
  public static final int por = 8;
  public static final int bool_literal = 59;
  public static final int sub = 12;
  public static final int coma = 47;
  public static final int obtenerporetiqueta = 63;
  public static final int not = 21;
  public static final int igual = 50;
  public static final int filtrar = 43;
  public static final int var = 23;
}

